.babelrc, circle.yml, package.json
Coverage testing breaks tests on some React components. For the moment, then, we need to remove it.
- Remove the coverage packages and integration.
- Switch CircleCI testing to just use the plain tests
- `npm prune`
- Run `npm test` and `npm run lint` and see that they pass
- See that the build passes on CircleCI with test results.
=> Remove coverage testing from the scaffold.

app/containers/app/container.js, package.json, styleguide.config.js
- Import and add `IconSprite` into the app container be default
- Run `npm install`
- [Preview the build](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- To confirm that the icon sprite is ACTUALLY working, you need to add an icon somewhere. Do this:
- Open `app/containers/app/container.js`
- Change `import {IconSprite} from 'progressive-web-sdk/dist/components/icon'` to `import {Icon, IconSprite} from 'progressive-web-sdk/dist/components/icon'`
- Add `<Icon name="cart-add" />` somewhere in the container
- Preview the page and confirm that the icon appears as expected.
=> Add Icons to scaffold

app/styles/_variables.scss
Due to popular demand, rename the Z-Index variables into something easier to use.
- Rename `z-index` away from the theatre stage analogy, and more toward a numbered unit.
- Confirm that you feel like this is a good change.
=> Rename z-index variables

app/loader.js
Since automatically extracting the path regexes from the router to the loader is taking a long time, this PR provides a means for controlling the React app loading based on manually-entered regexes. 
- Add a basic `isReactRoute` function to the loader
- Fall back to desktop when the function returns false
- Preview Merlin's Potions
- Observe that the React app continues to work correctly loading from the home page.
- Observe the desktop site at http://www.merlinspotions.com/books.html
- See that the React site reappears on navigating to the Potions section.
=> Fall back to desktop if the provided regexes don't match the path.

app/loader-routes.js, app/loader.js, package.json
This completes the automation of isReactRoute
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/100
- Modify the loader to import the regexes from `loader-routes.js`. 
- Add a placeholder `loader-routes.js` so that things will always compile
- Add an NPM script for running the route extraction. (This is a slow process that we probably can't do every build)
- Install an SDK on the linked branch
- npm run dev and preview
- see that it loads the React app on all routes (/potions.html and /books.html, for example)
- npm run update-loader-routes (this will produce a lot of irrelevant warnings)
- see that it only loads the React app on the correct routes, and not missing routes
=> Automatically generate loader route regexes

webpack/base.main.js
Adds an alias for local component so importing them is much simpler.
- Adds new `components` alias to the project's webpack configuration
- In the scaffold run `npm install`
- `npm run add:component` and follow the instructions naming the component `Test`
- Add `import Test from 'components/test'` to app/containers/home/container.js
- Also add `<Test text="hear me roar" />` to the container's render function
- Preview [Merlin's Potions](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.min.js&disabled=0&domain=&scope=1)
- Notice that the test component should appear on the home page
- Should the alias be more specific? Like `progressive-local-components` or something else equally contrived yet less likely to collide …
=> Add alias for components

package.json, styleguide.config.js, styleguide/Layout.css, styleguide/Renderer.jsx, styleguide/styleguide.scss
Project styles (`app/stylesheet.scss`) weren't being applied to the project styleguide (`npm run styleguide`)
- Add a `styleguide/` top-level directory, matching the SDK's implementation for applying styles to the styleguide
- Refactor styleguide's config to properly load all pieces
- Add a `styleguide/styleguide.scss` that simply imports the project stylesheet
- Checkout this code
- Create a new component in the project with `npm run add:component`
- Inside the newly generated component, modify its base styles with something easily identifiable (e.g. `background-color: $error-color;` Note the use of a project SCSS var)
- Add your new component's base styles to `app/styles/_components.scss`
- Run `npm run styleguide`
- Visit localhost:4000
- Ensure the newly generated component has the …
=> 🐛 Fix project styles missing inside styleguide

CHANGELOG.md, app/loader.js, package.json, webpack/base.common.js, webpack/base.loader.js, webpack/base.main.js, webpack/dev.js, webpack/production.js, webpack/styleguide.config.js
Add PostCSS for minification and autoprefixing of our CSS.
- Add PostCSS (Autoprefixer) to the loader and preloader
- Minify the CSS on production
- Add some missing settings for production's webpack settings
- `main.css`
- Run `npm i`
- Preview [Merlin's Potions](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2F0.0.0.0%3A8443%2Floader.min.js&disabled=0&domain=&scope=1)
- Confirm that styles are being applied
- Open [main.scss](https://0.0.0.0:8443/main.css?1472500281307)
- Confirm that browser prefixes are being added for things like `flexbox`
- No minification should be happening yet
- Run `npm run build`
- Open in your editor: `/build/main.css`
- Confirm that the CSS is minified
- `preloader.css`
- In your editor, open …
=> Add PostCSS (Autoprefixer) and Minification

CHANGELOG.md
Hotfix: A changelog item got added to the wrong spot. Moving it to the correct spot here.
- Move changelog item to correct spot ("To Be Release")
=> Move changelog note to correct location

webpack/dev.js
- Remove webpack dashboard from the webpack dev.js config
- checkout this branch
- Ensure the console outputs the original webpack build information, not the webpack dashboard.
=> Take out webpack dashboard

app/loader-routes.js, package.json
Previously we had to manually run `sdk-get-routes` to update the loader-routes. This ensures that it runs when the dev server starts so that we don't have to remember.
- Runs the sdk-get-routes script when the dev script starts up
- Updates the loader routes
- Update one of the routes in the `app/app-provider.jsx` file
- Kill the dev server and ensure that the loader-routes file changed to reflect your updated route.
=> Run get-routes on dev

.eslintrc.yml, app/components/logo/index.jsx, package.json
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/168
- Adds JSX a11y eslint plugin
- Updates code-style version to support a11y linting config
- Fixes a11y warning in default Logo component
- Checkout code
- `rm -rf node_modules/mobify-code-style/ && npm i`
- `npm run lint`
- Make a JSX a11y linting error or warning (like removing `role="presentation"` from `<Image ...`) and ensure eslint flags it
=> ✨ Add a11y linting

CHANGELOG.md, app/components/skip-links/_base.scss, app/components/skip-links/index.jsx, app/components/skip-links/test.js, app/containers/app/container.js, app/containers/home/container.js, app/styles/_components.scss, tests/system/page-objects/home.js, tests/system/site.js, tests/system/workflows/home-example.js
SkipLinks are an accessibility feature that should be included on all of Mobify's project *by default*. This way, screen reader users, assistive technology and keyboard users are able to skip to relevant content much more easily.
- Added SkipLink component to scaffold
- Added nightwatch tests that check to ensure the SkipLinks and their targets are valid (at least on the homepage)
- Make Merlin's Potions the default initial URL for local Nightwatch tests
- Preview [Merlins Potions](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.min.js&disabled=0&domain=&scope=1)
- (if testing in desktop Chrome) Ensure that dev tools is closed, and then...
- Click the browser's URL bar
- On your keyboard, press …
=> Add SkipLinks

tests/jest-setup.js, tests/system/site.js, webpack/base.loader.js
- Change the loader's output filename to `loader.js`
- Make sure Jest and Nightwatch tests still work as expected
* Clone the [Progressive Web generator](https://github.com/mobify/generator-progressive-web)
* Hop into the generator's generate.sh file and change line 5 to SCAFFOLD_VERSION_OR_BRANCH="change-loader-naming"
* Run the generator in the directory where your test project will be generated: `./path/to/generator/generate.sh`
* Accept the license and provide a test project slug
* Enter "http://www.merlinspotions.com" as the project URL (the URL must include the "http" protocol part for our `.preview()` Nightwatch command)
* Once the new testing project is generated, navigate into the directory
* Due to [this issue](https://github.com/mobify/generator-progressive-web/issues/2), run …
=> 🎨 Change output loader filename

package.json
Exposes the new command which was added to the SDK. Merge after the next SDK release - CircleCI tests will fail on this branch until then.
**JIRA**: https://mobify.atlassian.net/browse/WEB-771
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/206
- Run `npm install` to get latest SDK and run `npm run add:form` to generate the form boilerplate.
=> Include the new 'npm run add:form' command in package.json

.babelrc, app/main.jsx, dev-server/index.js, package.json, webpack/base.main.js, webpack/dev.js
Gets rid of the React hot loader.
**JIRA**: https://mobify.atlassian.net/browse/WEB-859
- Remove all references to the React hot loader
- Make sure you can preview Merlin's Potions
- Modify a component's code
- Verify that the browser didn't automatically refresh
- Manually refresh the page and verify the code changes are visible
=> Remove the React Hotloader

app/utils/magento-utils.js, app/utils/utils.js
This PR adds a utility function that extracts all of the information stored in JSON script tags by Magento on a page. It is not (yet) integrated with any parsers
**JIRA**: N/A
- Add the function
- import the function into a parser and add `console.log(extractMagentoJson($html).toJS())`
- see that it logs an object with useful information on load.
=> Add a utility function for extracting information from Magento JSON

app/utils/parser-utils.js, app/utils/parser-utils.test.js
We should parse elements like links and images in a uniform way, so I looked in the Crabtree and Lancome codebases for the parser utilities they found useful. This imports them to the scaffold and adds tests
- Add generic parsers for `a`, `button`, `img`, `option`, and `select` elements
- Add tests
- run the tests!
=> Add parser utils from the delivery builds with tests

app/styles/base/_typography.scss
Add more font weights for Oswald and Open Sans.
- Add more weights for Oswald and Open Sans, including specifically:
- Oswald: 300, 400, and 700
- Open Sans: 400, 400 italic, 600, 600 italic, 700, and 700 italic
- Preview the build (`npm run dev`) or the styleguide (`npm run styleguide`)
- Add the various different font weights to some text and ensure they apply as intended.
=> Add more font weights

package.json
Before, running `npm run styleguide` would fail to run. A certain `webpack-hot-middleware` dependency wasn't able to be found if running with npm version 2.x, so this change updates Styleguidist to the latest, and adds the middleware module as a dependency to the scaffold.
- Update Styleguidist to 4.1.0
- Add `webpack-hot-middleware` as a dev-dependency
- In the repo's root, run `rm -r node_modules/react-styleguidist && rm -r node_modules/webpack-hot-middleware` 
- Run `npm i`
- Run `npm run styleguide` and ensure that the style guide runs and is visitable.
=> Styleguidist Fix

app/app-provider.jsx, app/containers/app/actions.js, app/containers/app/constants.js, app/containers/app/reducer.js, app/containers/plp/reducer.js, app/containers/plp/reducer.test.js
The PLP has multiple URLs that match it, so if you were to receive multiple `onPageReceived` actions, each one would update the store and render --- but we only want to render the last one. This allows for us to compare the `onPageReceived` request URL to the current URL, and only render if it matches.
**JIRA**: [WEB-917](https://mobify.atlassian.net/browse/WEB-917)
- Provide the request url when dispatching `onPageReceived`
- Provide the current url when dispatching `onRouteChanged`
- Update the `app` store with the current URL, in the `app` reducer for the `onRouteChanged` action
- Add a new condition inside the PLP reducer to only update the store selector when the `onRouteChanged` url matches the current url
- Quickly click multiple PLP links by opening the navigation …
=> Allow components to restrict when they render

app/config/cache-hash-config.json
The baseDir for the cache hash manifest should be set to `app`.
- Set the `baseDir` to `app`.
- Preview Merlin's Potions.
- Open `tmp/cache-hash-manifest.json`.
- Look for `static/img/categories/potions@2x.png` and remember the hash value.
- On the Merlin's homepage, inspect the "Potions" category image.
- Make sure the image contains the hash value you remembered from the cache manifest.
=> Set the cache hash manifest baseDir correctly.

app/containers/app/container.js, app/containers/mini-cart/actions.js, app/containers/pdp/actions.js
Update the mini cart on add to cart, and on cart open
- Update the mini cart on add to cart
- Update the mini cart on mini cart open
- Add an item to the mini cart
- Observe the mini cart contents
- Add an item to the mini cart in another tab
- Observe the mini cart contents in the original tab after opening
=> Update the mini cart on add to cart, and on cart open

app/components/badge/README.md, app/components/badge/_base.scss, app/components/badge/index.jsx, app/components/badge/test.js, app/components/button/_theme.scss, app/containers/header/_header.scss, app/containers/header/container.js, app/containers/header/reducer.js, app/loader-routes.js, app/styles/_components.scss
Adds the logic for getting the Cart item count, as well as a badge component.
- Add Cart counter logic
- Add Badge component
- Preview [Merlin's Potions](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- Add a few items to the cart
- Confirm that the Cart count appears on top of the Cart button in the site header
=> Add: Cart Counter Logic & Badge

app/styles/_components.scss
I missed removing this import from today's earlier release of 0.10.4
=> Release Patch: Remove unnecessary CSS import

README.md, package.json
The certificate shipped with version 1.14.1 of `webpack-dev-server` is expired, as of March this year. This PR updates to a newer version with a non-expired cert.
With this PR in place, the `node_modules/webpack-dev-server/ssl/server.crt` certificate can be added to the trust store of a Mac to avoid having to re-confirm SSL exceptions for any progressive build with this change.
=> Improve preview SSL

app/containers/home/partials/home-carousel.jsx, app/containers/mini-cart/container.js, app/containers/pdp/partials/pdp-carousel.jsx, app/styles/_utilities.scss, app/styles/animations/_background.scss, app/styles/lib/_background.scss, app/styles/themes/pw-components/_skeleton-inline.scss, app/styles/utilities/_display.scss
Soften the skeleton animation colors and improve performance for some browsers.
- Switch `background-position` to animation to `transform` (drastically reduce paints)
- Switch from background gradient to `box-shadow`
- Switch from solid colors to opaque
- [Preview Merlin's Potions](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- Verify the skeleton animations look good
=> Tweak skeleton animations

webpack/base.worker.js, webpack/dev.js, webpack/production.js, worker/main.js
Adds the Webpack scripts necessary for building a service worker, and a stub service worker for them to build.
**JIRA**: Contributes to https://mobify.atlassian.net/browse/WEB-991
**Linked PRs**: https://github.com/mobify/progressive-web-scaffold/pull/175
- Add dev and production build scripts for the service worker.
- npm run dev
- see that http://localhost:8443/worker.js exists
- npm run prod:build
- see that there is a worker.js in the build directory.
=> Service worker build infrastructure

app/loader.js, package.json, service-worker-loader.js, worker/main.js
We need a service worker for Merlin's Potions to increase performance, improve our Lighthouse score, and enable offline mode and add to homescreen on Chrome. This PR will add one, along with the machinery needed to load it.
Functionality:
- A 'bundle cache' for bundle contents, that prevents requests from going onto the network.
- An image cache, for the 40 most recent images loaded. These images are served by the cache but updated from the network in the background.
- A general cache for all other content, with an expiration of 24 hours for content.
The current PR only works for local preview, production support will be added in a follow-up.
**JIRA**: https://mobify.atlassian.net/browse/WEB-991
**Linked PRs**: #193 
- Add a service worker build configuration
- Add a service worker file
- …
=> Service worker for Merlins - Phase 1

app/main.jsx, package.json, webpack/base.main.js
Since we need web push to still work for demos on Merlins Potions, and we are using a different cloud project than what is live (and is set up for web push) - we need to load the a.js file from a different slug. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-992
**Linked PRs**: #190, #195
- Support for separate a.js slug in `package.json` and used in `main.jsx`
- Preview
- Observe a.js loads from the right place (check the Network Debug Panel)
=> Support for using a custom a.js slug

.babelrc, app/containers/login/actions.js, package.json
This PR improves our build size in some simple ways.
**JIRA**: N/A
- Import only the necessary part of the `validator` package, saving 65KB uncompressed
- Use the Babel runtime transform to deduplicate glue code, saving 20KB uncompressed
- Preview the bundle, see that nothing's changed
=> Bundle analyzer improvements

circle.yml
Two main reasons for this change:
- Progressive Mobile is becoming part of this repo.
- We run into some issues with the new Lighthouse tests on CircleCI 2.0
Based on the above, now is not a good time to migrate to a new CI platform that hasn't been publicly released.
- Make sure CircleCI tests pass.
=> Revert back to CircleCI Classic.

package.json
It looks like the `prod:build` npm script got lost at some point in time... Seems rather important, so here it is again.
- Execute `npm run prod:build`
- Verify the production bundle gets properly built.
=> Add the prod:build npm script back.

native/app/controllers/tabBarController.js, native/app/controllers/tabController.js
Implements the pop-to-root when tapping on the tab you're already on. `TabController` owns this behaviour now.
- (change1)
- (necessary corresponding PRs)
=> Implement pop-to-root when tapping already-selected tab

native/app/app.js, native/app/config/baseConfig.js, native/app/config/tabBarConfig.js, native/app/controllers/tabBarController.js, native/app/controllers/tabController.js, native/webpack.app.config.js
Renames the alias for webpack from `astro` to `progressive-app-sdk`
- Rename the alias
- Go through each import and fix
- Run the app and navigate around
=> Rename astro to progressive-app-sdk in the imports

service-worker-loader.js, worker/main.js
This PR makes sure to store all of the assets necessary for the Merlins homepage in the bundle cache, which does not expire, rather than in the general cache, which lives for 24 hours. Many of these changes should be applicable to other sites as well, though testing will be required
**JIRA**: https://mobify.atlassian.net/browse/WEB-935
- Store Google fonts, home page HTML, and preview information in the bundle cache
- Update the worker loader script in the repo to match the deployed script
- Preview Merlins homepage
- Reload to ensure warm caches
- Set to offline in dev tools
- Reload and see that the home page still renders
- Delete the `progressive-web-scaffold-v0.1.2` cache in the Application tab of the dev tools
- Reload and see that the home page still renders
=> Ensure offline homescreen survives cache expiry

app/containers/app/reducer.js, app/containers/cart/reducer.js, app/containers/catalog/products/reducer.js, app/containers/checkout-confirmation/reducer.js, app/containers/checkout-payment/reducer.js, app/containers/checkout-shipping/reducer.js, app/containers/footer/reducer.js, app/containers/header/reducer.js, app/containers/home/reducer.js, app/containers/login/reducer.js, app/containers/mini-cart/reducer.js, app/containers/navigation/reducer.js, app/containers/pdp/reducer.js, app/containers/plp/reducer.js, app/loader-routes.js, app/utils/utils.js, app/utils/utils.test.js, package.json
The `redux-act` library is very helpful but is not very widely used. A similar library made by people close to the core Redux team is `redux-actions`.  This PR ports the scaffold from `redux-act` to `redux-actions`. 
A benefit to `redux-actions` is that its actions and reducers support a separate path for errors in each action, triggered by passing an `Error` object as the action parameter, which will cut down on the number of distinct actions in our application. It is also 13% smaller minified and gzipped. 
The main user-visible changes are in the reducer. The `handleActions` function takes the place of the `createReducer` function, and the individual action handler functions are now passed the full action object rather than just the payload. The utility function `createAction` has been …
=> Port the actions and reducers to `redux-actions`

app/containers/app/_app.scss, app/containers/app/container.js
Add sticky footer effect to Merlin's Potions
- Apply "sticky footer" effect to site
- Moved the `app--${currentTemplateProps.route.routeName}` class to live on the same element as `t-app`
- Test both tall pages (just about any existing page) and a short page (i.e. the [Confirmation page](https://www.merlinspotions.com/checkout/confirmation/) either before it gets merged, or on desktop after it gets merged.
- Ensure footer is sticky, and doesn't have any negative side effects on the functionality of the site (i.e. messing up how the site scrolls)
=> Make footer sticky across site

app/containers/app/actions.js, app/containers/app/actions.test.js, app/containers/app/container.js, app/containers/app/selectors.js, app/containers/cart/container.js, app/containers/cart/selectors.js, app/containers/footer/container.js, app/containers/footer/selectors.js, app/containers/header/container.js, app/containers/header/selectors.js, app/containers/home/container.js, app/containers/home/selectors.js, app/containers/login/container.js, app/containers/login/selectors.js, app/containers/mini-cart/container.js, app/containers/mini-cart/selectors.js, app/containers/navigation/container.js, app/containers/navigation/selectors.js, app/containers/pdp/container.js, app/containers/pdp/selectors.js, app/containers/plp/container.js, app/containers/plp/selectors.js, app/containers/reducers.js, app/store/index.js, app/store/selectors.js, package.json
This PR uses `reselect` to selectorize all access to the Redux state, and uses the latitude that grants to refactor the store a little. The data access patterns remain the same, including the passing of Immutable objects to React components.
- (change1)
- (necessary corresponding PRs)
=> Selectorize store access

app/containers/app/container.js, app/containers/cart/container.js, app/containers/footer/container.js, app/containers/footer/partials/footer-navigation.jsx, app/containers/header/container.js, app/containers/home/container.js, app/containers/login/container.js, app/containers/mini-cart/container.js, app/containers/navigation/container.js, app/containers/pdp/container.js, app/containers/pdp/selectors.js, app/containers/plp/container.js, app/containers/plp/selectors.js, app/store/selectors.js, app/utils/selector-utils.js, app/utils/selector-utils.test.js
This PR adds the `selectorToJS` utility function which will handle the Immutable -> JS conversion in a way that preserves the JS object. This, combined with writing the `mapStateToProps` function as a Reselect selector, allows `react-redux` to determine on its own whether a connected component needs to be updated.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1032
- Add utility functions for handling Immutable using Reselect
- Convert all the containers to use them
- Convert a number of containers to stateless components.
- Preview Merlins and see that everything works.
=> Remove Immutable from React components

app/containers/app/container.js, app/containers/app/selectors.js, app/containers/header/container.js, app/containers/header/selectors.js, app/containers/home/container.js, app/containers/home/selectors.js, app/containers/login/container.js, app/containers/login/selectors.js, app/containers/mini-cart/container.js, app/containers/mini-cart/selectors.js, app/containers/navigation/container.js, app/containers/navigation/reducer.js, app/containers/navigation/selectors.js, app/containers/pdp/actions.js, app/containers/pdp/actions.test.js, app/containers/pdp/container.js, app/containers/pdp/reducer.js, app/containers/pdp/selectors.js, app/containers/plp/container.js, app/containers/plp/selectors.js, app/utils/selector-utils.js
This PR breaks up access to the store contents into individual selectors for each member of the template (and catalog) objects. This is in preparation for both a) rearranging the store, and b) connecting the store closer to where the values are used.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1032
- Write more specific selectors
- Use them in `mapStateToProps` in lieu of the more general selectors
=> Break up store access

app/containers/footer/container.js, app/containers/footer/partials/footer-navigation.jsx, app/containers/footer/partials/footer-newsletter-subscription.jsx, app/containers/footer/partials/footer-social-icons.jsx, app/containers/footer/selectors.js, app/containers/header/container.js, app/containers/header/partials/cart-action.jsx, app/containers/home/container.js, app/containers/home/partials/home-carousel.jsx, app/containers/home/partials/home-categories.jsx, app/containers/home/reducer.js, app/containers/pdp/container.js, app/containers/pdp/partials/pdp-add-to-cart.jsx, app/containers/pdp/partials/pdp-carousel.jsx, app/containers/pdp/partials/pdp-carousel.test.js, app/containers/pdp/partials/pdp-description.jsx, app/containers/pdp/partials/pdp-description.test.js, app/containers/pdp/partials/pdp-heading.jsx, app/containers/pdp/partials/pdp-heading.test.js, app/containers/pdp/partials/pdp-item-added-modal.jsx, app/containers/pdp/selectors.js, app/utils/selector-utils.js
Splitting this stage of the refactor into smaller pieces because it's a big one. This PR re-architects the structure of the Header, Footer, Home, and PDP containers so that the Redux store is accessed closer to where the resulting data is used. Footer, Home, and PDP are now functional components with no props, making the top-level code very clean.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1032
- Connect the Redux store lower down the component tree
=> Connect further down in Header, Footer, Home, and PDP

package.json, webpack/dev.js
Now that the final 2.2 release of webpack has [officially been released](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.5y82q2fwm), this PR upgrades us to it. In future PRs, we will start to take advantage of some new features.
For now, we already benefit from a few improvements, such as the following console output to indicate big chunks when we build our production bundle.:
- Upgraded to webpack 2.2
- Replaced the `NoErrorPlugin` with the `NoEmitOnErrorsPlugin`
- Run `npm run dev` and preview Merlin's Potions.
- Verify that the site works as expected.
- Run `npm run prod:build`
- Verify that the production bundle gets built correctly.
=> Upgrade to webpack 2.2

app/styles/animations/_background.scss, app/styles/lib/_background.scss
Fixes Placeholder animation on iOS 10
**JIRA**: https://mobify.atlassian.net/browse/WEB-1100
- Minimize the size of the box in the pseudo element
- There's an Apple known issue where rbga colour is rendered darker on device (due to a rounding error of 0.02 - http://stackoverflow.com/questions/9338827/why-do-browsers-render-rgba-differently-on-osx). This is why the rectangle box is seen on device but not on Chrome desktop.
- Can only be seen on device
- Please follow the instruction in this ticket: https://mobify.atlassian.net/browse/WEB-1100
=> [WEB-1100]:  Fixes Placeholder animation on iOS 10

app/containers/app/actions.js, app/containers/app/actions.test.js, app/containers/app/reducer.js, app/containers/cart/partials/cart-promo-form.jsx, app/containers/catalog/products/actions.js, app/containers/catalog/products/reducer.js, app/containers/footer/actions.js, app/containers/footer/reducer.js, app/containers/footer/reducer.test.js, app/containers/header/reducer.js, app/containers/home/actions.js, app/containers/home/reducer.js, app/containers/login/actions.js, app/containers/login/reducer.js, app/containers/login/reducer.test.js, app/containers/navigation/actions.js, app/containers/navigation/reducer.js, app/containers/navigation/reducer.test.js, app/containers/pdp/actions.js, app/containers/pdp/reducer.js, app/containers/pdp/reducer.test.js, app/containers/plp/actions.js, app/containers/plp/reducer.js, app/containers/plp/reducer.test.js, app/utils/reducer-utils.js
This PR moves all parsing calls from reducers to actions. For most pages, this is done through a wrapper function called `process` in each action file, which takes the `onPageReceived` action as input and returns a new page-specific action with the parsed data. 
Ultimately, this is a step towards two things:
- Building an API barrier between the reducers and actions
- Reducing the processing in reducers as much as possible
To the second end, most of the new actions include a payload that can be directly merged with the state. This PR contains utilities to make this common case simpler.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1118
**Linked PRs**: #239 
- See that all pages load content as before
=> Decouple parsers from reducers. 

circle.yml
Lighthouse tests are broken for unknown reasons. A Jira ticket to further investigate that has been created. Half a day of research has not brought any clarity as to why this is happening.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1126
- Disabled Lighthouse tests.
- Validate CircleCI reports successful test results.
=> Disable Lighthouse tests for now

web/app/containers/catalog/products/reducer.js, web/app/containers/footer/actions.js, web/app/containers/footer/parsers/parser.js, web/app/containers/footer/parsers/parser.test.js, web/app/containers/footer/partials/footer-navigation.jsx, web/app/containers/footer/reducer.js, web/app/utils/parser-utils.js, web/app/utils/parser-utils.test.js
This PR introduces an Immutable Record type for a text link, as parsed by the `parseTextLink` function. The Record definition is temporarily placed in parser-utils.js in the absence of a general schema.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1118
- Introduce the Record definition
- Use it where necessary
- See that the footer and PLP continue to work correctly.
=> Schematize links

.github/PULL_REQUEST_TEMPLATE.md
Minor improvement to PR template
- Remove `(necessary corresponding PRs)` mostly because I haven't noticed it being useful... open to bringing it back
- Add basic runtime steps to get a PR up and running.
- Not sure this is testable
- Confirm if you like the template?
=> Add common necessary steps to PR template

web/app/styles/_lib.scss, web/app/styles/base/_typography.scss, web/app/styles/lib/_heading-level.scss, web/app/styles/utilities/_heading.scss
This is so we can add !important to the heading utility classes, which
wasn’t possible with extend.
- Replace the heading utilities' `@extend` declarations with mixin `@include`s instead.
- Heading utilities now have `!important`, as all utilities are intended to have.
- Visit any page with an html heading and confirm it's base styles have NO `!important`
- Find a head utility class and confirm it has `!important`
- Confirm that all heading levels (1-6) work as intended.
=> Replace @extend with @include

web/app/containers/app/selectors.js, web/app/containers/cart/selectors.js, web/app/containers/footer/selectors.js, web/app/containers/header/selectors.js, web/app/containers/home/selectors.js, web/app/containers/login/partials/register-form.jsx, web/app/containers/login/partials/register-panel.jsx, web/app/containers/login/partials/signin-form.jsx, web/app/containers/login/partials/signin-panel.jsx, web/app/containers/login/reducer.js, web/app/containers/login/selectors.js, web/app/containers/navigation/selectors.js, web/app/containers/pdp/selectors.js, web/app/containers/plp/selectors.js, web/app/store/cart/selectors.js, web/app/store/selectors.js, web/app/utils/selector-utils.js, web/app/utils/selector-utils.test.js, web/package.json
This PR adds some more utilities to `selector-utils.js`, and improves the functionality of some existing utilities. It also adds tests and documentation to those utilities, and refactors all of the selectors to use the new utilities.
This PR also contains an exploration of how selectors might be specified more cleanly in the login selector file (i.e. `web/app/containers/login/selectors.js`). Feedback is welcome, and I am willing to move it to a later time for further development/discussion.
**Linked PRs**: #239 
- run the tests
- check that things still work.
=> Improve the clarity of the selectors with better utilities

native/app/config/baseConfig.js
Points the app to the `astro` target on Cloud to allow people to test the BuddyBuild builds.
- (change1)
=> Astro: Point app to special *Astro* target bundle

web/app/containers/pdp/_pdp.scss, web/app/containers/pdp/partials/pdp-add-to-cart.jsx
Fixes Stepper on PDP on iOS 9.3
**JIRA**: https://mobify.atlassian.net/browse/WEB-1146
- Fixes the issue where the stepper component is squished on iOS 9.3
- use iOS 9.3
- Preview to: https://www.merlinspotions.com/
- Navigate to a PDP
- Look at the Quantity stepper
- The minus and plus icons should not be squished
=> WEB-1146: Fixes Stepper on PDP on iOS 9.3

web/app/app-provider.jsx, web/app/containers/app/actions.js, web/app/containers/cart/partials/cart-summary.jsx, web/app/containers/checkout-shipping/actions.js, web/app/containers/checkout-shipping/actions.test.js, web/app/containers/checkout-shipping/checkout-shipping-parser.js, web/app/containers/checkout-shipping/container.jsx, web/app/containers/checkout-shipping/partials/checkout-shipping-form.jsx, web/app/containers/checkout-shipping/partials/shipping-address.jsx, web/app/containers/checkout-shipping/partials/shipping-email.jsx, web/app/containers/checkout-shipping/partials/shipping-method.jsx, web/app/containers/checkout-shipping/reducer.js, web/app/containers/checkout-shipping/reducer.test.js, web/app/containers/footer/parsers/parser.js, web/app/loader-routes.js
This PR is some initial work related to moving the checkout shipping page over to the new Architecture. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1111
**Linked PRs**: n/a (larger PR will be opened for architecture-2.0-checkout-shipping)
- Update shipping page route so we can fetch the page content the same as we do on other pages
- Fixed JS error in the footer on checkout pages
- Parse and render the form title from the desktop HTML
- Refactored shipping sections into their own partials
- add an item to your cart
- the still …
=> Refactor checkout shipping partials

web/app/containers/checkout-shipping/actions.test.js, web/app/containers/checkout-shipping/container.jsx, web/app/containers/checkout-shipping/partials/checkout-shipping-form.jsx, web/app/containers/checkout-shipping/partials/shipping-address.jsx, web/app/containers/checkout-shipping/partials/shipping-email.jsx, web/app/containers/checkout-shipping/partials/shipping-method.jsx, web/app/containers/checkout-shipping/reducer.test.js
This PR disconnects the main checkout shipping container from the store, and instead connects partials to the store. **Note:** Selectors have not yet been added for this container, they will be added in a separate PR. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1111
**Linked PRs**: #292 
- Connect shipping-email and shipping-address partials to the redux store
- Disconnect checkout-shipping main container from the store
- add an item to your cart
- confirm that the page still works the same as it did before
=> Connect checkout shipping partials

web/app/containers/checkout-header/container.js
This removes default web header in the checkout flow. This is to match the looks of 
http://merlins-app.surge.sh/#artboard1
**JIRA**:  https://mobify.atlassian.net/browse/HYB-985
**Linked PRs**: #301
- if runninh in Astro return null else return header
- add an item to cart
- open the checkout modal
- press proceed to checkout
- on the top you shouldn't see a web header, you should see the checkout flow icons at the top
=> Astro: Merlins Remove web header in checkout

web/app/containers/checkout-shipping/actions.js, web/app/store/checkout/shipping/selectors.js
This PR adds the shipping data entered in the shipping form to the store under checkout -> shipping -> address. The data uses the same format that the form submission requires. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1111
- Added shipping data to the store under checkout -> shipping -> address
- Added selectors to access the address data
- add an item to the cart
- confirm that the page still works as expected
=> Persist shipping data

web/CHANGELOG.md, web/package.json, web/webpack/base.main.js
This PR adds the ability to analyze the build output. It is controlled using the `MOBIFY_ANALYZE` environment variable. 
**JIRA**: N/A
- Adds the webpack bundle analyzer plugin
- Checks `MOBIFY_ANALYZE` environment variable and adds it to the webpack plugin list if the value of the variable is `true`
- Opens the analyzer output on build completion
- Run `npm install`
- Run `MOBIFY_ANALYZE=true npm run prod:build`
=> Adds bundle analyzer to the scaffold

web/app/containers/checkout-payment/actions.js, web/app/containers/checkout-shipping/actions.js, web/app/store/checkout/selectors.js
This PR adds the users email address to the checkout store
**JIRA**: n/a
- Added the email address entered on the shipping page to the checkout store
- Added a selector for the emailAddress 
- Updated checkout payment submission to use email address data from the store
- add an item to your cart
- proceed to the checkout shipping page
- fill in all form fields (including email address)
- continue to the next step
- click "Place your order" (make sure you have the network tab open so you can examine the request sent)
- view the data sent
- you should see the email …
=> Checkout persist email

web/app/containers/app/actions.js, web/app/containers/app/actions.test.js, web/app/containers/app/constants.js, web/app/static/js/offline-test.json, web/dev-server/index.js, web/worker/main.js
Instead of writing our own custom fetch handler (and subsequently, a cache handling mechanism), use an alternative, simpler method of detecting if we're offline.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1029
**Linked PRs**: #265 
- Revert changes to worker `main.js` file to state prior to #265 
- Add a new JSON file `static/js/offline-test.json` which is requested each time a page is requested
- Add worker handler for this request URL which will provide a success response of `{offline: true}` when the network fails
- Update logic to app to detect this (instead of a response header), while keeping original app logic the same (for whether to display offline banners/splash screen, etc.)
- Preview [Merlin's …
=> Simpler method of offline detection

web/app/containers/pdp/partials/pdp-heading.jsx, web/app/containers/pdp/partials/pdp-heading.test.js, web/app/containers/plp/partials/plp-header.jsx, web/app/containers/plp/partials/plp-header.test.js
Removes the breadcrumbs from the PLP and the PDP if running in Astro
**JIRA**: https://mobify.atlassian.net/browse/HYB-1011
- Conditionally show breadcrumbs in PDP
- Conditionally show breadcrumbs in PLP
- Add tests for both
- Go to PLP, breadcrumbs shouldn't be there
- Go to PDP, breadcrumbs shouldn't be there
=> Remove breadcrumbs if running in Astro

web/app/app-provider.jsx, web/app/template.jsx, web/app/utils/astro-integration.js, web/app/utils/utils.js
Originally we started with using an Astro event to communicate the PWA navigation. I changed it to use an RPC method. At some point the changes to support the RPC on the web side got lost. This fixes the PWA side of in-app navigation.
**JIRA**: [HYB-962](https://mobify.atlassian.net/browse/HYB-962)
- Swift from using an Astro event to RPC method (this allows Astro to sit on the navigation while it swaps views before letting it continue)
- Expose `Astro.trigger` through `astro-integration` so that we only ever use `astro-integration` in the PWA.
- Run the app
- Navigate to some potions
- Navigate back using the header bar
Note: You'll know it's working if you get stacking. No stacking means it's broken!
=> Re-work Astro integration to support seamless back transitions

web/app/containers/pdp/partials/pdp-add-to-cart.jsx
This PR fixes a Prop Type warning on the PDP. 
**JIRA**: n/a
- Remove isRequired from quantity prop on the PDP
- Navigate to any PDP
- No prop type warning should show in the console
- Add 2 of the item to your cart
- Navigate to the cart and click "Edit"
- Confirm the correct qty (ie. 2) is shown on the edit version of the PDP
=> Fix PDP propType warning

web/app/store/cart/actions.js
Update the cart checking functionality with changes required when the Magento 'full page cache' is enabled.
**JIRA**: https://mobify.atlassian.net/browse/PLATT-95
**Linked PRs**: https://github.com/mobify/merlins-potions-magento/pull/14
- Added required parameters to the 'fetch cart contents' request
- Run against the Merlins backend build from the linked PR, or the live one (this change works for the backend with 'full page cache' both enabled or disabled)
- Add something to the cart - observe everything works now when interacting with a backend with 'full page cache' enabled.
=> Fix for cart state checking when Magento has full page cache enabled

web/scripts/build.sh
Fail project build if it detects error when Webpack is building. We want to ensure no bundle is uploaded to cloud if webpack or build script failed
Webpack doesn't exit with error code 1 without the `--bail` flag
Bash scripts needs `set -e` to propagate error up the chain
Make sure your are in a bad environment that the build should fail
```
rm -r /node_modules/node-sass/vendor/darwin-x64-51/
nvm use v7
```
Run either commands:
```
npm run push --m "Test - should not push"
// or
npm run prod:build
```
**Expected:** Neither command should succeed
=> Fail build when web pack failed

web/app/config/merlins-potions-nearby-config.json, web/app/containers/home/_home.scss, web/app/containers/home/container.js, web/app/containers/home/partials/home-nearest-stores.jsx
Remove Nearest Store widget on home page. Will need to add more work to Nearest Store widget when we get final answer from Product Manager and designer. It will not be on home page, it will be on different page. 
**JIRA**: https://mobify.atlassian.net/browse/PLATT-43
- remove Nearest Store Widget on home page
- add placeholder to nearest store partial 
- Make sure that there is no Nearest Store Widget on home page.
=> PLATT-43: nearby widget fix

native/app/controllers/tabBarController.js, native/app/controllers/tabController.js
Fixes the previous broken back button on Android
- TabbarController handles the closes
- on Android go on shop -> product listing page
- press the hardware back button, should go back navigation and once it is at root, it should close the app.
=> Astro: Merlin's Android back button handling

web/app/containers/app/actions.js, web/app/containers/app/container.js, web/app/containers/app/reducer.js, web/app/containers/app/selectors.js
**JIRA**: https://mobify.atlassian.net/browse/WEB-1241
**Linked PRs**:
https://github.com/mobify/crabtree-evelyn-progressive/pull/575
https://github.com/mobify/lancome-progressive/pull/843
**Before**
**After**
- Remove importing of SVG file into the bundle
- Add actions/reducers/etc. to pull in the SVG file via Ajax
- Verify icons appears fine
- Run `MOBIFY_ANALYZE=true npm run prod:build`
- View the Webpack Analyzer report and verify that the SVG sprite is no longer in the App files
=> WEB-1242: Remove SVG from bundle

web/app/containers/app/actions.js, web/app/loader.js
**JIRA**: https://mobify.atlassian.net/browse/WEB-1233
**Linked PRs**:
https://github.com/mobify/crabtree-evelyn-progressive/pull/572
https://github.com/mobify/lancome-progressive/pull/846
**Before**
**After** Saves about ~0.5s
- A flag to keep track of initial entry to the site
- Retrieved the captured document's html if initial entry
- Confirm in Chrome's network tab that we are not requesting homepage twice.
- Confirm you can still navigate to other parts of the site successfully
=> WEB-1233: Prevent duplicate page request by using initial captured doc

web/app/containers/product-details/actions.js
Added to cart modal “go to checkout” goes to shipping page when it should link to cart
- Added to cart modal “go to checkout” goes to cart
- Add an item to cart and click on "Go to checkout"
=> Added to cart modal “go to checkout” goes to shipping page 

web/app/containers/product-list/partials/product-list-contents.jsx
**JIRA**: https://mobify.atlassian.net/browse/WEB-1228
**Linked PRs**:
- SDK regression introduced by: https://github.com/mobify/progressive-web-sdk/pull/511
- SDK fix (not released yet): https://github.com/mobify/progressive-web-sdk/pull/529
- Unwrap the 'no results' content from `List` component. Verified that the `List` component didn't have any styling impact on the 'no results' contents
- I've checked the site, it appears this regression only happens when we have 1 children inside the `<List />` component.  Another note.. if we have a map with only 1 item, it'll still work with the `<List />` component.
- Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled …
=> WEB-1228: Hot fix singular list children regression

web/app/containers/cart/partials/cart-product-list.jsx, web/app/containers/cart/partials/cart-summary.jsx, web/app/containers/checkout-header/container.js
Letter spacing of link text is too big (affecting multiple areas including the checkout header at 320px)
- set letter-spacing to initial for links in cart and checkout
- Proceed to checkout
=> fix letter spacing in cart and checkout

web/app/containers/cart/partials/cart-summary.jsx
Cart promo code should be in an accordion
- move promo code in an accordion
=> move promo code in an accordion

web/app/containers/cart/partials/cart-summary.jsx, web/app/containers/checkout-payment/partials/billing-address-form.jsx, web/app/containers/checkout-payment/partials/credit-card-form.jsx, web/app/containers/checkout-payment/partials/order-summary.jsx, web/tests/system/page-objects/product-details.js
H4 formatting in cart and checkout should be all CAPS
- add uppercase utility class to elements with h4 formatting
- add item to cart and go through the checkout
- check "h4" headings are in CAPS
=> add uppercase utility class to elements with h4 formatting

web/app/containers/checkout-payment/actions.js, web/app/containers/checkout-shipping/actions.js, web/app/containers/login/container.js, web/app/containers/navigation/container.js, web/app/containers/product-details/actions.js, web/app/router.jsx, web/package.json
This PR removes all direct references to `react-router`, instead importing the re-exports from the SDK. This prevents version skew leading to duplication of the code in the final bundle. This decreases our vendor.js on Merlin's by 5kb gzipped, to 150kb. 
**JIRA**: N/A
- Remove react-router dependency
- Import `browserHistory` and `withRouter` from the SDK
- No longer pass our own `browserHistory` object since we're accessing the one in the SDK.
- npm i
- See that it still works (particularly the switching between tabs on the login page changing the URL and proceeding through the checkout)
=> Remove local react-router

web/app/containers/product-details/actions.js, web/app/containers/product-details/actions.test.js, web/app/store/cart/actions.js, web/app/utils/magento-utils.js, web/app/utils/utils.js
When the 'full page cache' is enabled on the Magento backend, add-to-cart flow changes a little. This PR fixes the PWA so it remains functional.
**JIRA**: https://mobify.atlassian.net/browse/PLATT-95
**Linked PRs**: #363, https://github.com/mobify/merlins-potions-magento/pull/19
- Bugfix for checking cart contents request
- Include logic flow discovered from Magento JS for properly dealing with `form_key` when adding to cart
- Add to cart
- Try again with cookies cleared (or in incognito)
- Make sure it works in both cases
- Run your own Merlins instance locally, based on [this …
=> Fix Add to Cart when Magento Full Page Cache is enabled

web/app/containers/checkout-shipping/partials/shipping-email.jsx
No default text in email field, should read “Email Address”
- add placeholder to email address
- Proceed to checkout to get to shipping step
=> Add email placeholder

web/app/containers/product-details/actions.test.js, web/app/integration-manager/demandware-connector/commands.js, web/app/integration-manager/merlins-connector/home/parser.test.js, web/app/integration-manager/merlins-connector/navigation/parser.test.js, web/app/loader-routes.js, web/app/main.jsx, web/app/router.jsx
This PR adds fetching navigation data to the demand ware connector, and adds a route for the demandware homepage.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1256
- Added demandware home page to router
- Added command to fetch root level categories from the demandware API 
- Set up tag injector for the demandware sandbox (http://mobify-tech-prtnr-na03-dw.demandware.net/on/demandware.store/Sites-2017refresh-Site/default/Home-Show)
- Preview [the demandware site](https://preview.mobify.com/?url=http%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- View the categories on the homepage and in …
=> Home page demandware connector

web/app/containers/cart/partials/cart-product-list.jsx
buttons below stepper have extra padding
- remove extra padding to have text on one line
- go to cart on (320px device) and check buttons are in one line
=> remove extra padding to have text on one line

web/app/containers/cart/partials/cart-estimate-shipping.jsx, web/app/containers/mini-cart/container.js, web/app/containers/navigation/_navigation.scss, web/app/containers/navigation/container.js, web/app/styles/themes/pw-components/_sheet.scss
fix width for right and left modals
- Change to global menu - remove the fixed width on .t-navigation .c-sheet__wrapper
- Change the style of pw-sheet_wrapper c-sheet_wrapper from left/right: 20% to 15%
- Apply max-wdith of 340px to pw-sheet_wrapper c-sheet_wrapper (to apply to main navigation drawer, estimate shipping modal and anything else that uses a side drawer)
- check modals that open from right and left
=> fix width for right and left modals

web/app/integration-manager/_demandware-connector/app/commands.js, web/app/integration-manager/_demandware-connector/commands.js, web/app/integration-manager/_demandware-connector/constants.js, web/app/integration-manager/_demandware-connector/home/commands.js, web/app/integration-manager/_demandware-connector/index.js, web/app/integration-manager/_demandware-connector/parser.js, web/app/integration-manager/_demandware-connector/product-details/commands.js, web/app/integration-manager/commands.js, web/app/main.jsx
This PR updates the demandware connector to match the reorganized merlins connector.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1256
**Linked PRs**: #423
- Move home and PDP commands for demandware connector into their own folder
- Set up tag injector for the demandware sandbox (http://mobify-tech-prtnr-na03-dw.demandware.net/on/demandware.store/Sites-2017refresh-Site/default/Home-Show)
- Preview [the demandware site](https://preview.mobify.com/?url=http%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- The homepage should work correctly
=> [Integration Manager] Reorganize demandware connector

web/app/integration-manager/_demandware-connector/commands.js, web/app/integration-manager/_demandware-connector/product-details/commands.js
This PR fixes a couple errors introduced from the demandware IM reorg work. 
**JIRA**: n/a
- Fix import path for DW product responses
- Fix export structure for DW commands 
- Set up tag injector for the demandware sandbox (http://mobify-tech-prtnr-na03-dw.demandware.net/on/demandware.store/Sites-2017refresh-Site/default/Home-Show)
- Preview [the demandware site](https://preview.mobify.com/?url=http%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- Confirm the home page and a PDP still work as expected 
- PDPs for "master" products will not be able to be added to the cart, this issue is addressed …
=> Fix PDP reorganization fixes

web/app/containers/navigation/actions.js, web/app/containers/navigation/container.js, web/app/containers/navigation/reducer.js, web/app/integration-manager/_demandware-connector/app/commands.js, web/app/integration-manager/_demandware-connector/commands.js, web/app/integration-manager/_demandware-connector/constants.js, web/app/integration-manager/_demandware-connector/home/commands.js, web/app/integration-manager/_demandware-connector/index.js, web/app/integration-manager/_demandware-connector/parser.js, web/app/integration-manager/_demandware-connector/parsers.js, web/app/integration-manager/_demandware-connector/product-details/commands.js, web/app/integration-manager/commands.js, web/app/main.jsx, web/app/utils/utils.js
This PR updates the site navigation to work with child categories, and fixes the demandware navigation parsing to return the correct structure for the NavMenu component. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1256
- Fixed demandware navigation parser to return correct structure
- Added action/reducer to show navigation panels correctly.
- Set up tag injector for the demandware sandbox (http://mobify-tech-prtnr-na03-dw.demandware.net/on/demandware.store/Sites-2017refresh-Site/default/Home-Show)
- Preview [the demandware site](https://preview.mobify.com/?url=http%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disab …
=> [Integration Manager] Demandware navigation fixes

web/README.md
**JIRA**: none
**Linked PRs**: none
- Adds instructions for preventing SSL errors on Windows machines. During training we have to do this every time to reduce the number of errors/warnings first time users see in their consoles when running the scaffold for the first time.
- Updates instructions to use `npm` scripts for saving credentials and deploying bundles. The old instructions involved using `grunt` and checking that the `mobify-client` node module is installed (which we don't seem to install by default).
- Read the instructions. I've followed the SSL instrcutions before with Windows 7/10 users and I just tried them out on a Windows 10 VM with success.
- Have not tried the bundle instructions today but I've seen them work in the past...except on Windows where our script will error …
=> Windows instructions for avoiding SSL errors. Bundle push instructions update.

web/app/components/product-item/index.jsx, web/app/containers/cart/partials/cart-product-list.jsx, web/app/containers/checkout-payment/partials/payment-product-item.jsx, web/app/containers/product-details/_product-details.scss, web/app/containers/product-details/partials/product-details-item-added-modal.jsx, web/app/containers/product-list/partials/product-tile.jsx
Cart product card’s columns not set as per mocks, should be % width so that the image gets bigger on larger devices
- add a prop to product item for width% and make modal shrink to content
- go to PDP and add an item to cart
=> Fix image width and modal

web/app/containers/checkout-payment/_checkout-payment.scss, web/app/containers/checkout-payment/partials/credit-card-form.jsx, web/app/styles/_animations.scss
Animate ‘add a new card radio’ to new position
- transition padding on add new card
- animate add new card form
- Add an item to cart and checkout 
- on payment step switch between add new card and saved card
=> add animation to 'add new card' section

web/app/loader.js
- Remove Favicons
We noticed that all three of the favicons are downloaded onto the device. We originally expected only one to download. Additionally, having our favicons didn't prevent the desktop favicon from being downloaded.
To save on bandwidth (even if a bit), we're removing the three favicons.
- Verify in Chrome Inspector that only the original desktop favicon is downloaded, but none of the three CDN hosted favicons.
=> Remove favicons

web/app/utils/utils.js
Fixing a small bug resulting from extracting the method `extractPathFromUrl`
**JIRA**: N/A
**Linked PRs**: https://github.com/mobify/platform-scaffold/pull/440
- Use the constructed `urlObject` to get the hash instead of the `url` string.
- Open the hamburger navigation
- Navigate to one of the entries (this is where it was broken previously)
=> Fix `extractPathFromUrl` helper method

web/app/containers/footer/partials/footer-social-icons.jsx, web/app/containers/home/partials/home-categories.jsx
- Add unit `px` to image prop values to prevent errors from appear, for example like...
- Scroll to the bottom of the page to trigger any lazy loaded images (including footer icons!)
- Navigate to the PLP and PDP pages
- Verify that the above images no longer appear in console
=> Add Units to Image Width Prop

native/package.json
Updates to the latest released version of the progressive-app-sdk
- Update package.json in native folder
- `cd native && npm run deps`
- Run app, no need for preview
=> Update to latest released astro version

web/app/loader.js
In Astro,  until we decide whether we want to show a preloader and what that preloader will look like, we'll disable the preloader.
**JIRA**: https://mobify.atlassian.net/browse/HYB-1040
- Don't display preloader if in Astro
- Preview in app by running app (preview is on by default)
- You shouldn't see any header preloader when opening the cart, for example
=> Don't show preloader if running in Astro

web/app/containers/product-details/selectors.js, web/app/integration-manager/_merlins-connector/products/commands.js, web/app/integration-manager/_merlins-connector/products/parsers.js, web/app/integration-manager/_merlins-connector/products/parsers.test.js
This PR prevents some unnecessary work and removes the `formInfo` from the `ui->product-details` store branch, since it is now handled entirely within the Merlin's connector. This simplifies the Product Details UI parser significantly.
**JIRA**: Preparatory for moving to the SDK
- Don't pass the `formInfo` to the UI branch
- Don't parse extra data in the form parser that is immediately discarded
- Miscellaneous changes.
- Visit a PDP and see that it still renders and works correctly.
=> Clean up product code a little

web/app/containers/app/reducer.js, web/app/containers/app/selectors.js, web/app/containers/cart/actions.js, web/app/containers/navigation/container.js, web/app/integration-manager/_demandware-connector/categories/commands.js, web/app/integration-manager/_demandware-connector/products/commands.js, web/app/integration-manager/_merlins-connector/categories/commands.js, web/app/integration-manager/_merlins-connector/categories/parser.js, web/app/integration-manager/_merlins-connector/products/commands.js, web/app/integration-manager/_merlins-connector/products/parsers.js, web/app/store/categories/actions.js, web/app/utils/utils.js
This PR removes the `urlToPathKey` function from the scaffold in favour of the version found in SDK 0.14.1. 
**JIRA**: N/A
- Change all imports to get the function from the SDK
- Remove the local definition
- `npm i`
- Make sure nothing has broken.
=> Convert urlToPathKey to use the SDK version

web/app/components/lazy-load-content/README.md, web/app/components/notification-manager/README.md, web/app/components/notification/README.md, web/app/components/product-item/README.md
The component README files were generated with incorrect import statements for the Javascript of the component. This fixes them so that no tool thinks we're missing a dependency called `components`.
**JIRA**:  N/A
=> Use relative paths for components in the READMEs

native/app/config/baseConfig.js
I noticed we were still using the old version that we published to get around issues with not having a published bundle when we started development. We should point this to the production bundle.
- Change CDN URL to point to `production` instead of `astro`
- Run app in Release Mode
- Should work as expected
=> Update astro default bundle to be production

web/app/containers/cart/partials/cart-product-list.jsx
Sign in cta in cart for Merlins PWA is still visible when logged in
**JIRA**: https://mobify.atlassian.net/browse/WEB-1327
- display 'sign in' only when user is not loggedIn
- Go to cart
- Login then go to cart
=> WEB-1327: do not display sign in when user is loggedIn

native/app/app.js, native/app/config/baseConfig.js, web/app/loader.js
Also restore control of preview toggling to the PreviewController
**JIRA**: https://mobify.atlassian.net/browse/HYB-1010
**Linked PRs**: #304
- Remove disable service worker in Astro check
- Restore control of preview toggling to the PreviewController
- Enable port forwarding to your Android device with chrome://inspect (localhost 8443)
- Run the Android app
- Shake to enable preview prompt
- Enable preview
- Kill app
- Make some local changes to your bundle you can easily verify
- Run app again
- Observe Preview display comes up
- Observe via Chrome Debugging tools a service worker exists
- Preview
- Observe your local changes are visible
=> Re-enable the service worker since it’s become preview-aware

native/app/config/baseConfig.js, native/app/controllers/accountTabController.js, native/app/controllers/cartModalController.js, native/app/controllers/tabBarController.js, native/app/controllers/tabController.js, native/app/controllers/tabHeaderController.js
Previously we were creating a new cart every time we wanted to open it. These carts were never released and you end up with a bunch of orphaned controllers/webviews. We now create one cart and reuse it.
**JIRA**: https://mobify.atlassian.net/browse/HYB-1025
- Pass around one cart modal controller
- Run app
- Open/close cart a bunch of times
- See in Safari that only one cart has been created/is instantiated
=> Use only 1 cart

web/app/containers/product-details/partials/product-details-carousel.jsx
hide pips and image navigation when there is only one image
**JIRA**: https://mobify.atlassian.net/browse/WEB-1333
- add a condition to not display controls when there is 1 image
- [Go to PDP](https://www.merlinspotions.com/unicorn-blood.html)
=> WEB-1333: add a condition to not display controls when there is 1 image

web/app/containers/app/container.js, web/app/containers/cart/container.js, web/app/containers/checkout-shipping/container.jsx, web/app/containers/home/container.jsx, web/app/containers/login/container.js, web/app/containers/login/container.test.js, web/app/containers/offline/container.jsx, web/app/containers/product-details/container.jsx, web/app/containers/product-list/container.js, web/app/containers/templates.js, web/app/router.jsx
By separating the Template HoC from the actual template components, the React Loadable work made the `fetcher` functions not work. This PR rearranges things so that they will work again. 
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-56
- Wrap the template components in their own `container.js`, as long as they've been converted to the Integration Manager from the old `fetchPage` action. (the IM changes broke the circular dependency)
- Write a wrapper component for Loadable to simplify `templates.jsx` and the lazy-load of the templates in the App component.
- See that all of the …
=> [Integration Manager] Fix interaction between Loadable and Template HoCs.

web/app/containers/product-list/partials/product-list-contents.jsx, web/app/containers/product-list/selectors.js, web/app/integration-manager/_merlins-connector/categories/parser.js, web/app/integration-manager/_merlins-connector/categories/parser.test.js
The text on the PLP when there were no available products was parsed out of the PLP HTML. This PR removes that in favour of a built-in string. 
**JIRA**: N/A
- Use a string in the code rather than a parsed string when there are no items
- No longer pick out the string in the Merlin's parser.
- Go to an empty category (e.g. Charms)
- See that there is still text
- See that the text is not stored in the categories branch of the Redux store.
=> No longer parse plp text

web/app/containers/product-details/container.js, web/app/containers/product-details/partials/product-details-description.jsx
rearrange content so product description is placed below the buying options
**JIRA**: https://mobify.atlassian.net/browse/WEB-1334
- move product detail accordion
- make it open by default
- go to PDP
=> move product details accordion and open by default

web/app/containers/product-details/actions.js, web/app/containers/product-details/partials/product-details-add-to-cart.jsx, web/app/containers/product-details/partials/product-details-carousel.jsx, web/app/containers/product-details/partials/product-details-description.jsx, web/app/containers/product-details/partials/product-details-heading.jsx, web/app/containers/product-details/partials/product-details-item-added-modal.jsx, web/app/containers/product-details/partials/product-details-variations.jsx, web/app/containers/product-details/selectors.js, web/app/integration-manager/_demandware-connector/cart/utils.js, web/app/store/products/selectors.js
This PR separates the selectors for the product information in the store from the selectors for the product details UI data. 
**JIRA**: N/A (but found while working on https://mobify.atlassian.net/browse/WEBDATA-10)
- Move product selectors to `app/store/products/selectors.js` so they aren't so tied to the ProductDetails container.
- Preview and see that nothing has changed.
=> Move product selectors out of the product details branch

web/tests/system/page-objects/checkout.js, web/tests/system/page-objects/home.js, web/tests/system/workflows/guest-checkout.js, web/tests/system/workflows/home-example.js, web/tests/system/workflows/registered-checkout.js
Verify email and numeric input types on certain fields
- Verify that email field on homepage is email type
- Verify that email field for log in (on checkout) is email type
- Verify that phone number field is numeric type
- Verify that password field is password type
- `npm run smoke-test`
- or Rebuild on CI: https://circleci.com/gh/mobify/platform-scaffold/tree/verify-input-types
=> Verify input types

web/CHANGELOG.md, web/package.json
**Linked PRs**: #549 (is blocked by this PR)
- Update SDK to 0.14.6
- Run `npm update progressive-web-sdk`
- Verify the App still runs as intended
=> Update SDK version to 0.14.6

web/app/containers/product-list/partials/product-list-contents.jsx, web/app/containers/product-list/partials/product-list-header.jsx, web/app/containers/product-list/selectors.js, web/app/store/categories/actions.js, web/app/store/categories/selectors.js
This PR moves the selectors related to the `categories` branch of the store into the `store` directory tree where they belong, and rewrites the other code to match. It also uses the new method of getting the parent category link (following the schema refactor)
**JIRA**: N/A
- Split out and rename category selectors
- Edit the PLP code to use the new selectors
- See that everything still operates on the PLP
=> [Integration Manager] Split out category selectors

web/app/containers/product-details/actions.js, web/app/containers/product-details/partials/product-details-variations.jsx, web/app/integration-manager/_demandware-connector/products/commands.js
The blur event triggered an update of the product images if the user selects a variation, and blurs off of the `<select>`
This PR changes the `onBlur` handlers to an `onChange` for when
the user selects a different variation of an item on the PDP
Prior to this, if a user changed their "item variations" and immediately
clicked "add to cart", the blur event would instead fire, preventing the add
to cart - thus requiring a second click
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-66
- Switched `onBlur` event to update image to `onChange` on PDPs
- Open `app/main.jsx`.
- Import the Demandware connector:
- Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site …
=> Fix - PDP Product Variant selection requires two clicks

web/app/containers/checkout-payment/partials/payment-product-item.jsx
The payment page wasn't updated when the cart schema was changed. This PR fixes that so the payment page gets the correct cart data.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-50
- Update PaymentProductItem component to get correct format for cart items
- Updated price rendering to match cart page
- Add an item to the cart and proceed through the checkout to the payment page
- The page should render correctly, including the order summary section below the payment/billing sections
=> [Integration Manager] Fix payment page rendering

web/CHANGELOG.md, web/README.md, web/package.json
This PR is based on a discussion with 64 Labs. They couldn't remember how to run the script as there was no script for it in the project's package.json.
- Add `analyze-build` as an NPM script to the build
- Update the web readme
- Run `npm run analyze-build`
- Once that's complete, the bundle analyzer page should open
=> Add analyze-build npm script

web/app/containers/product-list/partials/product-list-contents.jsx, web/app/containers/product-list/selectors.js, web/app/integration-manager/_merlins-connector/products/parsers.js
This PR fixes the missing product skeletons on the PLP
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-82
- Returned filtered results in `getFilteredProductListProducts` only if at least 1 filter is selected
- The products will be `undefined` until the product data is parsed, so this PR also adds a fallback in the product list contents partial to ensure that accessing `id` of `undefined` doesn't throw any errors 
- Navigate to a PLP, ensuring the skeleton appears
=> Fix to PLP missing skeletons

web/app/containers/checkout-payment/partials/payment-product-item.jsx, web/app/integration-manager/_merlins-connector/cart/parser.js
This PR removes the `getHighResImage` call from the `payment-product-item` partial
- removes the `getHighResImage` call from the `payment-product-item.jsx` partial, as it was already being called in the Merlin's-specific parser `/_merlins-connector/cart/parser.js`, as seen below
```javascript
{
thumbnail: {
src: getHighResImage(product_image.src),
alt: product_image.alt,
size: { /* See getHighResImage which has size hard-coded */
width: '240px',
height: '300px'
}
}
```
- Add a product to cart and ensure high res thumbnail is still properly being loaded on Merlin's connector
=> Integration manager - Merlins specific getHighResImage

web/app/styles/themes/_pw-components.scss
Previously, some custom SDK component styles would be overridden (beaten) by base styles due to the CSS cascade. For example...
```scss
@import 'node_modules/progressive-web-sdk/dist/components/button/base';
@import 'pw-components/button';
@import 'node_modules/progressive-web-sdk/dist/components/icon/base';
```
In the above example, if our custom `button` style had something to do with specific `icon` variation, the icon base could override our custom button's icon style.
Thus, to get around this, all custom styles are imported AFTER all the base styles to ensure developers have complete control over the SDK component styles.
- Re-order SDK component imports so local customization imports come after all base style imports
- Preview [Merlin's …
=> [Polish] Reorder theme imports

web/app/store/categories/parsers/product-list.js
Adding a change to remove a product that no longer works pre-Integration Manager
- TEMPORARY change to remove a product on Merlin's which no longer works with the current branch. This particular product supports variants, which isn't supported by the current release, but will be once the Integration Manager changes ship.
- Make sure https://www.merlinspotions.com/potions/eye-of-newt.html isn't in the list of products on `/potions.html`
=> Adding a change to remove a product that no longer works pre-Integration Manager

web/app/integration-manager/_merlins-connector/checkout/commands.js
There are a few requests on Merlin's that don't work with `fetch` for some reason. Since raw `XMLHttpRequest` is a pain to work with we use `$.ajax` instead, but it still doesn't fit well into our Promise-based workflow. This PR adds a utility function that wraps $.ajax with a Promise-based interface and centralizes all usage of that function.
- Encapsulate $.ajax in a Promise wrapper.
- Preview Merlin's
- See that the checkout still works with no 400 errors
=> Add a utility to encapsulate $.ajax for Merlin's

web/app/containers/checkout-shipping/partials/shipping-method.jsx, web/app/integration-manager/_merlins-connector/checkout/commands.js, web/app/integration-manager/_merlins-connector/checkout/parsers.js, web/app/integration-manager/_sfcc-connector/checkout/commands.js, web/app/integration-manager/checkout/results.js, web/app/integration-manager/checkout/types.js, web/app/store/checkout/reducer.js, web/app/store/checkout/selectors.js, web/app/store/checkout/shipping/selectors.js
This PR schematizes the shipping methods in the Redux store and integration manager, and moves them out of the `shipping` branch. 
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-69
- Create the schema types and actions
- Dispatch matching data from the connectors
- Accept matching data in the UI
- Preview Merlin's and DW
- See that the shipping options on the shipping page still work
=> [Checkout Schema] Schematize shipping methods

web/app/containers/onboarding/container.jsx, web/app/native/onboarding/onboarding.jsx
So whether or not messaging is enabled, the order is correct. 
**JIRA**: https://mobify.atlassian.net/browse/HYB-1044
- Store the app on-boarding carousel data in an array instead of an object
- `npm run deps` in `native/`
- Run `npm run dev` in `web/
- Run the iOS or Android app
- Observe the onboarding order is correct
- Toggle `messagingEnabled` in `package.json` in both `native/` and `web/`, re-run test, observe the order is still correct
=> Store the app on-boarding carousel data in an array instead of an object

web/app/integration-manager/_sfcc-connector/cart/utils.js, web/app/integration-manager/_sfcc-connector/checkout/commands.js
This PR fixes a bug on the SFCC confirmation page where the user's basket wasn't getting cleared after completing an order.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-49
- Added "createNewBasket" function to cart utils
- Called createNewBasket once an order has been placed
- Preview the [SFCC Site](https://preview.mobify.com/?url=https%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- add an item to your cart
- proceed through the checkout to complete the order
- click "continue shopping" on the confirmation page
- the mini-cart should show as empty when you reach the homepage
=> SFCC confirmation page bug fix

web/app/template.jsx
**NOTE:** The ticket describes this issue as occurring only on PLPs, but this would happen on any route change to an uncached page.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-92
- Placed the `checkIfOffline` dispatch after the `catch` for a route's fetchActions, thus allowing for offline mode to be set even if a fetch action fails
- Use Merlin's Connector
- Clear your cache in Application tab of dev tools (named progressive-web-scaffold-<version>)
- Turn on offline mode in applications tab or network tab in dev tools
- Navigate somewhere, and make sure that …
=> Fixes the offline mode hanging on uncached pages

web/app/containers/checkout-payment/actions.js, web/app/containers/checkout-payment/actions.test.js, web/app/containers/checkout-payment/partials/billing-address-form.jsx, web/app/containers/checkout-payment/partials/checkout-payment-form.jsx, web/app/integration-manager/_merlins-connector/checkout/commands.js, web/app/integration-manager/_merlins-connector/checkout/parsers.js, web/app/integration-manager/_sfcc-connector/checkout/commands.js, web/app/integration-manager/checkout/results.js, web/app/store/checkout/billing/selectors.js, web/app/store/checkout/reducer.js, web/app/store/checkout/selectors.js
This PR moves the billingSameAsShipping key to the root of the checkout store.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-69
- Renamed the billingSameAsShipping input to follow our naming conventions (ie. no underscores)
- Moved billingSameAsShipping to the root of the checkout store (results, reducers, selectors updated)
- Updated commands & actions to handle new location for billingSameAsShipping key
- Created new selector for billing address initial values that combines billingAddress with billingSameAsShipping
- add an item to the cart
- proceed through …
=> [Checkout Schema] move billingSameAsShipping key

web/app/containers/checkout-shipping/actions.js, web/app/containers/checkout-shipping/partials/shipping-method.jsx, web/app/integration-manager/_merlins-connector/checkout/commands.js, web/app/integration-manager/_sfcc-connector/checkout/commands.js, web/app/integration-manager/_sfcc-connector/checkout/parsers.js, web/app/integration-manager/checkout/results.js, web/app/store/checkout/reducer.js, web/app/store/checkout/shipping/selectors.js
This PR moves the selected shipping method ID to be a child of the checkout state. It also renames the shipping method input to match out naming conventions (ie. no underscores).
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-69
- renamed shipping method input
- added receiveSelectedShippingMethod to checkout reducer
- moved selected shipping method if out of the shippingAddress branch and into the checkout branch
- add an item to the cart
- proceed through the checkout to the shipping page
- fill out the address form
- select a shipping method other than the …
=> [Checkout Schema] move selected shipping method

web/app/integration-manager/_merlins-connector/app/commands.js, web/app/loader.js
- Uses HTML from the captured document on first load instead of re-fetching the page the user is already on. This helps to bring the overall load times down!
- Load the homepage
- Ensure that there isn't a second request for the homepage
=> Remove double download

web/app/containers/cart/partials/cart-product-list.jsx
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-91
**Linked PRs**: https://github.com/mobify/platform-scaffold/pull/669
- Hide the cart variants in cart product list
**NOTE:** This will be _properly_ fixed on Merlin's & SFCC connectors post-launch of the IM. This is a temporary solution to hide the hard-coded variants.
- Add something to cart
- Ensure that in the cart product list, the variants don't show as `Maroon` and `XL`
=> Hide the cart variants in cart product list

web/app/integration-manager/_sfcc-connector/parsers.js, web/app/integration-manager/_sfcc-connector/products/commands.js
Fix image filtering / PDP 404 errors
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-104
- Fix PDP productID regex
- add checks for if variants are present or not 
- Use sfcc connector
- Try navigating to men -> unisex gloves, or grand theft auto under electronics, and ensure the API request doesn't 404 and that you can proceed with checkout
=> PDP 404 fixes & variant fallbacks

web/app/integration-manager/_sfcc-connector/utils.js
Not all browsers support sessionStorage. This PR adds a function to check if session storage is supported and if it's not use cookies instead to track SFCC auth and basket data. 
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-98
- Added function to check if sessionStorage is supported
- Replace calls to set/get/remove from sessionStorage with function that will use cookies if sessionStorage is unsupported
- Preview [SFCC site](https://preview.mobify.com/?url=https%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1) in a private Safari window
- Navigate through the site and confirm it works …
=> Update sfcc connector storage

web/app/loader.js, web/webpack/base.main.js, web/webpack/dev.js, web/webpack/production.js
Previewing a bundle from the CDN will attempt to load the main worker module from `https://localhost:8443/worker.js` - which will not work.
- Instead of `IS_PREVIEW` boolean testing for a `mobify-path=true` cookie, look at the build origin of the `loader.js` script and evaluate to `false` if `cdn.mobify.com` is found
- Change `IS_PREVIEW` name to `IS_LOCAL_PREVIEW` to be a little more descriptive
- Add to Webpack config. to add DefinePlugin `DEBUG` value to loader file (both dev and production configs)
- Use `DEBUG` value from Webpack build process to pass to Messaging Client init instead, which is more accurate
- Also add a `resolve` handler for `react` so that `npm link progressive-web-sdk` can be used without error
- Run `npm run upload`
- Preview the preview URL it returns for the …
=> Fix worker loading

web/app/containers/checkout-confirmation/actions.js, web/app/containers/checkout-confirmation/actions.test.js, web/app/containers/login/actions.js, web/app/integration-manager/_merlins-connector/account/commands.js
This PR fixes the bug preventing registration of new user accounts. It also reads the Magento messages cookie to get the correct error message for the register and login forms.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-120
- No longer pass the password confirmation value into the command
- Duplicate the password in the Merlin's connector for registration
- Check that the passwords match in the confirmation page registration form
- Read the error message out of the `mage-messages` cookie rather than using a hard-coded value
- Preview Merlin's
- Attempt to register with a new email address (e.g. `yourname+webdata120@mobify.com`) 
- See that it works
=> [WEBDATA-120] Fix password confirmation

web/app/containers/checkout-payment/partials/billing-address-form.jsx, web/app/containers/checkout-shipping/partials/shipping-address-fields.jsx
This PR updates the full name label for the shipping and billing forms. Mitch asked me to do this as part of the work for WEBDAT-114 (#700) but I forgot to include it in that PR. 
**JIRA**:  https://mobify.atlassian.net/browse/WEBDATA-114
- Changed shipping form full name label to First & Last Name
- Changed billing form full name label to First & Last Name
- add an item to the cart and proceed to the shipping page
- the full name field should now be labeled "first & last name"
- fill out the form and proceed to the billing page
- uncheck billing same as shipping
- the …
=> Update labels for full name field

web/app/containers/navigation/container.jsx, web/app/integration-manager/_stub-connector/README.md, web/app/integration-manager/_stub-connector/account/commands.js, web/app/integration-manager/_stub-connector/actions.js, web/app/integration-manager/_stub-connector/app/commands.js, web/app/integration-manager/_stub-connector/cart/commands.js, web/app/integration-manager/_stub-connector/categories/commands.js, web/app/integration-manager/_stub-connector/checkout/commands.js, web/app/integration-manager/_stub-connector/commands.js, web/app/integration-manager/_stub-connector/config.js, web/app/integration-manager/_stub-connector/home/commands.js, web/app/integration-manager/_stub-connector/index.js, web/app/integration-manager/_stub-connector/products/commands.js, web/app/integration-manager/_stub-connector/reducer.js, web/app/integration-manager/_stub-connector/selectors.js, web/app/main.jsx
This PR adds an extremely basic connector which just stubs out all of the expected commands. This is to give partners who need to create a brand new custom connector a place to start from.
- Create stub connector
- Create stubs for all commands the integration manager expects
- Include some utility commands inside the app commands to make things like page fetching, offline mode easier
- In main.jsx, register the stub connector 
```
import {Connector} from './integration-manager/_stub-connector'
```
=> Add Stub Connector

web/app/integration-manager/_merlins-connector/actions.js, web/app/integration-manager/_merlins-connector/cart/commands.js, web/app/integration-manager/_merlins-connector/selectors.js
`formInfo` would return `undefined` in some rare intermittent cases during checkout. When that occurred, the `Add to Cart` button would remain disabled.
This PR fixes the add-to-cart remaining disabled, thus unblocking checkout.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-112
- Add a check for the intermittent empty form info to unblock addToCart
- Use merlins connector
1. Browse to https://www.merlinspotions.com/books/dragon-breeding-for-pleasure-and-profit.html
2. Click Add to Cart (should work)
3. Browse to https://www.merlinspotions.com/potions/unicorn-blood.html
4. Add to …
=> [WEBDATA-112] Check for empty forminfo value in addToCart

amp/app/__mocks__/svgMock.js, amp/app/containers/app/container.jsx, amp/app/containers/home/container.jsx, amp/app/main.js, amp/app/main.test.js, amp/app/templates/amp-page.js, amp/package.json
```
Fix AMP validation errors which are breaking tests.
- The amp-sidebar must be a direct child of the body tag for it to
be valid. Render the <body> in react to fix.
- Provide a Jest mock to stub out webpack imports of SVG assets which
are not needed during testing.
```
- Run `npm run test` locally - not captured by CircleCI at the moment, I guess.
=> Fix amp validation errors when using the Sheet component

web/app/integration-manager/_sfcc-connector/categories/commands.js
Currently the SFCC integration does not properly render an empty PLP when there are 0 products.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-107
- Add response checks for empty product returned
- In `/web/app/main.jsx`, import SFCC connector and comment out merlins connector
- Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1) **Note: use SFCC preview link**
- Navigate to Gift Certificates page, which should show no results instead of skeleton that go on forever.
=> Handle empty Product Listing Pages from SFCC

web/app/containers/app/actions.js, web/app/containers/cart/actions.js, web/app/integration-manager/_sfcc-connector/cart/commands.js, web/app/integration-manager/_sfcc-connector/cart/utils.js, web/app/integration-manager/_sfcc-connector/checkout/commands.js, web/app/main.jsx
This PR adds checks for cart expiry to the cart pages commands. *Note* this PR is just part of the work for WEBDATA-108, further work needs to be done to handle cart expiry on the checkout-shipping and checkout-payment pages. 
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-108
- created app action to show cart expiry message & navigate to homepage (this will be used on the checkout-shipping and checkout-payment pages too)
- created SFCC cart util to check if a basket has expired, if it has create a new one and throw an error
- added check for cart expiry to add to cart command & retry add to cart on new cart 
- added check for cart expiry to remove and update item cart commands 
- switch to the SFCC connector
- Preview the [SFCC …
=> Fail gracefully on cart page when SFCC basket Expires

web/scripts/install-google-chrome-stable.sh
A number of builds recently started failing mysteriously at the step to install the latest stable version of Chrome. See https://circleci.com/gh/mobify/lancome-progressive/5070?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
The solution was to add a `--fix-broken` flag to `apt-get` to resolve missing/broken dependencies, and to ensure the build ran on Ubuntu 14.04 (setting in CircleCI). While the mysterious failures were not observed on platform-scaffold, this PR adds the flag anyway, just in case. 
**Linked PRs**: https://github.com/mobify/lancome-progressive/pull/977
- Add `--fix-broken` flag when installing latest Chrome
- Rebuild https://circleci.com/gh/mobify/platform-scaffold/tree/chrome-dependency
- Ensure there are no errors in the log in …
=> Chrome dependency

amp/app/main.js, amp/package.json, amp/scripts/watch.js
Enable request logging for easier debugging. Prompted by the observation that the AMP validator makes x5 duplicate requests for each resource.
- Run `npm i`
- App should run as normal and log requests in the terminal.
=> Log requests on the AMP server

web/app/loader.js
Feedback from Sapient/Debenhams via @cdegit was that our PWA's are missing a `<meta charset='utf-8'>` tag (which should be added to avoid XSS attacks).  More info on this page: https://developer.mozilla.org/en/docs/Web/HTML/Element/meta
**JIRA**: N/A
- As it says in the title.
~~- [ ] (if applicable) analytics events instrumented to measure impact of change~~
- Open dev tools and view the *Elements* tab. Verify there is a `<meta>` tag that has the `charset` property set to `'utf-8'`.
=> Add <meta charset='utf-8'> tag

web/app/integration-manager/_merlins-connector/categories/commands.js, web/app/integration-manager/categories/types.js, web/app/store/categories/selectors.js
This PR adds the description key to the category schema to support the tutorial.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-100
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/680
- Added description key to category types in IM
- Added description to PLP parsing in Merlins Connector
- Added description selector to category selectors
- Follow the steps in part 2 of the tutorial (see PR linked above, not the tutorial that's currently live)
- Expand the description section on the resulting starters kit page
- You should see text there that matches the …
=> Add description to category schema

amp/app/containers/app/_base.scss, amp/app/containers/home/container.scss, amp/app/containers/product-details/container.scss, amp/app/containers/product-list/container.scss
Our Home template looks great, but the PLP and PDP have giant icons and the nav bar doesn't look right. This PR fixes that.
- Add missing style includes to the stylesheets of the PLP and PDP
- Run `npm test`
- Check http://localhost:3000, http://localhost:3000/potions.html, http://localhost:3000/eye-of-newt.html
=> Add missing styles for PLP and PDP

amp/app/components/product-item/README.md, amp/app/components/product-item/_base.scss, amp/app/components/product-item/index.jsx, amp/app/components/product-item/test.js, amp/app/components/product-tile/README.md, amp/app/components/product-tile/_base.scss, amp/app/components/product-tile/index.jsx, amp/app/components/product-tile/test.js
This PR adds components that are needed for the _PLP_ in **AMP-61**, it isn't the build-out of the _PLP_ itself.
**JIRA**: https://mobify.atlassian.net/browse/AMP-61
- Added in `ProductItem` component, styles, test and README
- Added in `ProductTile` component, styles, test and README
- Removed skeleton since we won't be needing it
- Visit `localhost:3000`
- I added this code to a template to ensure that it worked, along with styles pulled in: `<ProductTile className="hi" href="/" price="$200" title="product" thumbnail={{alt: "test", src: "/static/mobify.png"}}/>`
=> AMP-61: ProductItem and ProductTile Components

amp/app/data-integration/connectedStore.js, amp/app/data-integration/product-details-reducer.js, amp/webpack.config.js
Make our own minimal reducers or simply stop using reducers that we don't need, in order to not end up importing code that relies on `window` and other web browser facilities to exist. 
- Add our own `product-details` reducer
- Stop importing the PWA's `header` reducer
- Remove code rewriting config from webpack config
- Check out http://localhost:3000, http://localhost:3000/eye-of-newt.html, http://localhost:3000/potions.html
=> Remove dependency code patching for integration manager usage

web/app/store/categories/selectors.js
- Rename productPath selectors missed from this PR https://github.com/mobify/platform-scaffold/pull/711
=> Fix selector names referencing productPaths

amp/app/containers/app/container.jsx, amp/app/main.js, amp/app/templates/amp-page.js, amp/app/templates/font-serve.js
Font Changes
- Add Google fonts
- `wf-active` class same as PWA
- remove `amp-border-box` class, no longer need it
- Preview [Merlin's Potions](http://localhost:3000/)
- Check if Oswald font is working
=> AMP: Font changes

appveyor.yml, web/package.json
AppVeyor tests on windows break. This PR will fix that.
**JIRA**: N/A
- add `cross-env` to `package.json` test command
- Check that appveyor passes
=> [HOTFIX] Tests on AppVeyor

web/tests/system/test-scripts/check-lighthouse-score.js
- Specify the path to the Lighthouse reports in one place
- Rebuild on CI
- Verify that `check-lighthouse-score.js` can still find the Lighthouse reports
=> Pull out the Lighthouse reports directory into a var

web/app/containers/onboarding/_onboarding.scss, web/app/containers/onboarding/container.jsx, web/app/native/onboarding/onboarding.jsx
Onboarding styles (for Native) were broken. This change fixes them!
- Add missing `app` id to onbaording wrapper to make utility classes work again
- Add missing `t-onboarding` class
- Add missing styles to ensure height of onboarding carousel is correct
- ~~(if applicable) analytics events instrumented to measure impact of change~~
- Make sure you are in the `/native` directory
- Run `run deps`
- Follow the `/native/readme.md` instructions to preview the app
- When the onboarding screen appears, **verify** that its styles are correct
=> Fix broken onboarding styles

amp/app/containers/footer/container.jsx, amp/app/containers/footer/partials/footer-navigation.jsx
Make footer links go to the canonical site, remove email subscription (for now)
- Remove newsletter subscription until we fix our CORS headers for Merlins
- Make footer links go to the right places
- http://localhost:3000/potions.html - look at the footer and tap on the links
=> Footer updates

web/app/containers/login/partials/common.jsx, web/app/containers/login/partials/register-form.jsx, web/app/containers/login/partials/signin-form.jsx, web/app/styles/themes/_pw-components.scss, web/app/styles/themes/pw-components/_password-input.scss
use passwordInput component in login and registration forms
**JIRA**: https://mobify.atlassian.net/browse/WEB-1419
- use passwordInput in sign in and registration form
- Go to login page and check sign in and register forms
##Note
- We need to merge and publish https://github.com/mobify/progressive-web-sdk/pull/716 first then merge this
=> use passwordInput component in login and registration forms

web/app/connectors/_merlins-connector/products/parsers.js
Certain images were getting stretched due to a mismatch in height/width ratios. The assets that we were using and the values that we were forcing upon them did not quite match.
- Remove from our product parser where we override the product thumbnail with the images from the PDP carousels (they aren't the right dimensions for use in the thumbnails)
- ~~(if applicable) analytics events instrumented to measure impact of change~~
- Visit a Product List page and note that height/width of the product thumbnails (they should look good)
- Click any of the products to visit its PDP and let it …
=> Fix Stretched Product Thumbnails

amp/package.json, amp/scripts/build/build.js, amp/scripts/bundles.js
**JIRA**: https://mobify.atlassian.net/browse/AMP-46
- Change build script to build zip files (which Cloud expects)
- Provide  a `bundles.js` script for management of bundles on cloud.
- Include basic upload and list commands for the endpoints we have.
The list command is a little bare at the moment - we need it to show which version is the active one, which we can only do once we have deployments actually going through Cloud.
- Set up and run Cloud locally.
- Set your machine up with the superuser credentials for deployment:
```
➜  amp git:(amp-46--upload-command) cat ~/.mobify
{
"username": "fixture+super.user@test.com",
"api_key": "asdf"
}
```
- Run:
```
npm run build
./scripts/bundles.js upload project-41 build/[commit].zip
./scripts/bundles.js list project-41
```
You should see a …
=> AMP-46 - bundle upload command

web/app/connectors/_sfcc-connector/app/commands.js
- Updates the import path for Modal constants, which was previoulsy not updated on SFCC connector
- Use SFCC connector
- Ensure webpack doesn't throw and compile-time errors
=> Fix SFCC modal import path

web/tests/system/test-scripts/verify-build-size.js
I forgot a `run` in `npm run prod:build` 😓 
- Delete your `build` folder
- `npm run test:build-size`
=> Missed a 'run' in the help text

web/webpack/base.main.js
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-149
~~**Linked PRs**: (links to corresponding PRs, optional)~~
- Updated regex to no longer match against any string instance of `webpackJsonp`, and instead also optionally match against the entire `webpackJsonpAsync` string.
- Test the regex against `webpackJsonp`, `webpackJsonpAsync`, and `webpackJsonpAsyncAsync` strings
=> Fix JsonpAsyncAsync Webpack Console Error

web/app/loader.js
Loads app in parallel with the service worker
- Currently, all of our files necessary for the rendering of the app don't get loaded until *after* the Service Worker downloads. This hurts TTI by [what seems to be upwards of 2.5 seconds](http://www.webpagetest.org/result/170626_ZN_1CE1/)!
- Also loads web push in parallel with the app so that it's compilation + execution doesn't cause blocking later.
- Also ensures that you don't need the SW to successfully install in order to use the app.
- @Cdok  ensure that your issue doesn't happen anymore.
=> Loads app in parallel with the service worker

web/app/loader.js, web/app/utils/loader-utils.js, web/tests/system/page-objects/push-messaging.js, web/tests/system/workflows/push-subscribe.js
Recent changes to `loader.js` broke the loading of Messaging Client as well as the order of app load and Init Promise initialization.
- Since `loadAndInitMessagingClient` is no longer added to an array of deferred promises, remove "thunk" and just call the script load directly
- Add new method `addMessagingClientInitPromise` that sets up the Init Promise on window before `vendor.js` is loaded
- Modify error conditions in the script loading function - to avoid throwing multiple errors in console on error
- On the second page view, ensure you are shown the `DefaultAsk` messaging ask prompt …
=> Fix messaging client load and init promise

web/app/store/categories/selectors.js, web/app/store/checkout/billing/selectors.js, web/app/store/checkout/selectors.js, web/app/store/checkout/shipping/selectors.js, web/app/store/user/selectors.js
I know that these things are getting moved into the SDK, but these fixes will need to be there when we move this code anyways so may as well get it in. Currently not having a default object returned by selectors that we are building other selectors off of can result in hard-to-track-down errors. We've seen this when building out a sample "My Account" page in training and the selector for custom user content doesn't return an empty Map() by default.
**JIRA**: none
**Linked PRs**: none
- Return an `Immutable.Map()` as the default for selectors for the "custom" portions of the store.
- Make …
=> Immutable.Map() as default in selectors for custom branches of the store

web/app/loader.js
So, I thought that `vendor.js` contains everything in `node_modules` but that doesn't seem to be the case. For safety, set up the Messaging promises before both `main.js` and `vendor.js` are loaded.
**Linked PR**: https://github.com/mobify/platform-scaffold/pull/855
- Move `createGlobalMessagingClientInitPromise` above `main.js` and `vendor.js` loading in loader.js
- Messaging should be loaded, and DefaultAsk shown on the second page visit
=> Relocate the setup of messaging promise in loader

web/app/store/index.js, web/package.json, web/webpack/base.main.js
Make sure Mobify GA ID is lives in the `package.json` so that platform generator can update it
**JIRA**: https://mobify.atlassian.net/browse/MTT-652
- move where ga-id is defined
Expected: Mobify GA analytics are firing
=> Change where modify ga id is defined

web/README.md, web/package.json, web/tests/system/test-scripts/run-all-tests-on-ci.sh, web/tests/system/test-scripts/start-test-server.sh, web/tests/system/workflows/guest-checkout.js, web/tests/system/workflows/home-example.js, web/tests/system/workflows/push-subscribe.js, web/tests/system/workflows/registered-checkout.js
To reduce confusion, we want to make the test commands explicit when we're testing on production.
- `npm run test:e2e-prod` will test without preview the siteUrl in the package.json
- Removes the 'magic' of our setup scripts which detects git branch and associate master with the production environment 
- Update Readme
- Update this with the new nightwatch-commands
- npm run test:e2e-prod
=> Make it Explicit when we're testing on the Production Environment

amp/app/containers/product-details/partials/product-details-carousel.jsx
Fix carousel props on PDP: `previousIcon` and `nextIcon` does not work with `<Carousel>`
- Preview [Merlin's Potions](http://localhost:3000/potions/eye-of-newt.html)
=> remove this props, does not support on carousel

web/tests/system/page-objects/product-details.js, web/tests/system/workflows/guest-checkout.js, web/tests/system/workflows/registered-checkout.js
- Keep track of whether the product is in stock or not
- Condition the rest of the tests (after adding item to cart) on whether the product is in stock
- Rebuild https://circleci.com/gh/mobify/platform-scaffold/tree/e2e-sold-out
- If testing the sold out case, set `PRODUCT_LIST_INDEX` and `PRODUCT_INDEX` to 2
=> Skip the rest of the tests if a product is sold out

amp/package.json
Don’t run our `postinstall` logic when building for production, because it won’t work, and we don’t need it
**Linked PRs**: #801 
- Conditionally run `postinstall` logic based on node env
- `npm i`
- Make sure everything works as normal
- `npm run build`
- Make sure build is successful
=> Fix for building for lambda breakage

amp/DEVELOPING.md
Adds docs for finding application logs for the AMP backend on AWS Lambda
**JIRA**: https://mobify.atlassian.net/browse/AMP-87
**Reviewers**: @kschmidtdev @olibrook 
- Adds docs to `amp/DEVELOPMING.md`
- Read through the docs and make sure it makes sense
=> Added docs for finding logs on CloudWatch.

web/app/styles/base/_forms.scss
When focusing on input fields on Merlins, the interface zooms
**JIRA**: https://mobify.atlassian.net/browse/WEB-1469
- change input font-size to 16px
- Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1) on iphone
- open search and check it doesn't zoom in
=> change input font-size to 16px

web/package.json
Note: This PR is additive, we won't be removing `npm run dev` yet
=> Adds `npm start` to package.json npm scripts

amp/app/main.js
**JIRA**: https://mobify.atlassian.net/browse/AMP-97
**Status**: WIP - Opened for visibility
**Reviewers**: @kschmidtdev @olibrook 
- Add new analytics component to AMP App to account for new amp-ga-id if available
- Edit `./amp/package.json` to add new field 'ampgaAccount` and set it to a random id.
- Open the networks tab on chrome debugger and visit `localhost:3000/potions.html` and ensure two analytics requests are sent. You can search for your newly set ID or `ampgaAccount` to find the new analytics request.
TODO:
=> Amp 97 configures amp ga in generator

web/package-lock.json, web/package.json
Updates `node-sass` to v4.5.3 which adds better support for node 8.
**JIRA**: *n/a*
**Linked PRs**: *n/a*
- As stated in the description
- Switch to node 8
- `rm -rf node_modules`
- `npm install`
- while installing it should _*not*_ compile the sass library but instead download a pre-compiled variant (this is why we're updating this dep)
=> Update node-sass to v4.5.3

web/app/connectors/hybris-connector/categories/commands.js, web/app/connectors/hybris-connector/categories/parsers.js, web/app/connectors/hybris-connector/config.js, web/app/connectors/hybris-connector/utils.js
This PR covers pagination, sorting and filtering functionality in the initProductListPage command.
**JIRA**: ([MBFYCNCT-51](https://thinkwrap.jira.com/browse/MBFYCNCT-51))
-  Added pagination
-  Added sorting options
-  Added filters
-  Added parseFacets to categories/parsers.js
- Preview [Thinkwrap accelerator](https://preview.mobify.com/?url=https%3A%2F%2Fhydemo-electronics.thinkwrap.com%2Fyacceleratorstorefront%2Felectronics%2Fen%2F%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- Navigate to a category using the main navigation menu (e.g. Clothes > T-shirts > T-shirts your
- play around with pagination, sort options and filters.
=> Feature/mbfycnct 51 init product list page pagination, sorting and filters

web/app/connectors/_sfcc-connector/parsers.js, web/app/utils/utils.js
This PR updates the order status displayed for SFCC to match desktop. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1433 & https://mobify.atlassian.net/browse/WEB-1434
- Add util to convert string to title case
- Add function to determine order status based on SFCC order object
- Use util in`parseOrder` and `parseOrdersResponse`
- Switch to the SFCC connector
- Preview the SFCC site
- log in to an account that has orders
- view the orders list page and the order details page
- the status listed on each page should match the status shown on desktop
=> Update the order status for SFCC to match desktop

web/app/connectors/_merlins-connector/products/commands.js, web/app/styles/_modals.scss
**JIRA**: https://mobify.atlassian.net/browse/WEB-1425
**Linked PRs**: https://github.com/mobify/platform-scaffold/pull/934
- Fix modal styling when adding to cart from wishlist
- Only show "You need to select product options" if product options exist
- Test editing wishlist items, ensuring "You must select product options" only shows up on Eye of Newt
- Test adding to cart from wishlist on Magento connector, ensuring that the modal is properly anchored to the bottom of the screen
=> Resolve modal issues on Wishlist page

web/app/loader.js, web/package.json
The v8.1 tag, when previewing, will use the currently published bundle version of `loader.js`. That version of `loader.js` will then (when previewing) load the localhost version of `loader.js`. This means that you need both the published version and your local version to be aware of the v8.1 tag.
Merlin's published bundle is aware, but `master` branch is not. This means that newly generated projects using the scaffold (i.e. based on `master` branch) will fail when previewing the site.
**NOTE**: These changes should be ignored when merging `develop`! They are an attempt at a hotfix only.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1513
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/827
- Inject a `<body>` tag before referencing it when attempting to create React …
=> Hotfix for v8.1 tag updates

web/app/connectors/_merlins-connector/account/parsers.js, web/app/loader.js
This PR prevents iOS from auto formatting phone numbers. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1512
- Add meta tag to prevent format detection
- Update order details parser to handle possible <a> wrapped around address phone numbers
- Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1) using the iOS simulator 
- sign in to an account with orders placed
- navigate to a view order page
- phone numbers should appear without <a> tags wrapped around them
=> WEB-1512: fix phone number detection

web/app/containers/account-address/actions.js, web/app/containers/account-address/partials/account-address-fields.jsx
**JIRA**: https://mobify.atlassian.net/browse/WEB-1511
- Merlin's connector does not support "address names"
- For this reason, the form field was taken out of the UI
- Since the SFCC connector requires an address name, our UI is now generating an ID which it passes to the connector
- Try SFCC & Merlin's connectors
- Login to mobifyqa@gmail.com
- Navigate to the account address page
- Attempt to add addresses on both connectors
=> Generating unique string IDs for SFCC adding address

web/app/loader.js
If the `entryTypes` doesn't contain any supported entries (e.g. Safari 11)
https://w3c.github.io/performance-timeline/#dom-performanceobserver-observe()
**Related PR**: https://github.com/mobify/lancome/pull/312
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-242
- Should not see error in Safari <= 11
=> Catch error from trackTTI

web/app/loader.js, web/package.json, web/webpack/base.loader.js
We don't yet want to release the non-pwa feature until the September release. Add a package.json controlled flag (injected at build-time via webpack), and use that flag in loader.js to disable it.
- Add `nonPwaEnabled` boolean to `web/package.json`, with value `false`
- Update the webpack `base.loader.js` config to add a `NON_PWA_ENABLED` value at build-time
- Update `web/app/loader.js` with a local variable named `nonPwaEnabled`
- Use the local `nonPwaEnabled` variable to guard against the entire NonPwa code branch
- Using Charles, Map Remote `https://cdn.mobify.com/sites/progressive-web-scaffold/production/loader.js` to `https://localhost:8443/loader.js`
- View the desktop site without preview (and without mobile emulation)
- There should be no network requests for a …
=> Disable non-pwa feature

web/app/containers/header/actions.js, web/app/modals/more-menu/container.jsx
This PR updates the forward and back buttons in the A2HS header so they use the browserHistory object to go back & forward through the app. Previously the two buttons handled this behaviour inconsistently (one through window.history one through browserHistory.push) this meant there was never a forward state if you used the back button in the header.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1498
- Use `browserHistory.goForward()` for forward button in the A2HS more menu
- Use `browserHistory.goBack` for back button in A2HS header bar
- Remove code that pulls back URL off the state
- checkout the `develop` branch of the SDK
- cd into the SDK folder
- run `npm link`
- cd into the scaffold folder
- run `npm link progressive-web-sdk`
- run `npm run dev`
- Preview …
=> WEB-1498: Use browser history goBack and goForward functions A2HS

web/CHANGELOG.md, web/app/connectors/_merlins-connector/app/commands.js
This PR resolves a bug where a user is unable to log back in after logging out of their account. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1493
- Store form_key in a cookie so it gets sent with all requests
- log into an account
- open the menu and click sign out
- open the menu and click sign in
- log back into your account
- you should be able to log in again
=> WEB-1493: Store form key cookie on app initialization

web/CHANGELOG.md, web/README.md, web/package.json, web/tests/e2e/page-objects/home.js, web/tests/e2e/page-objects/product-list.js, web/tests/e2e/workflows/guest-checkout.js, web/tests/e2e/workflows/home-example.js, web/tests/e2e/workflows/push-subscribe.js, web/tests/e2e/workflows/registered-checkout.js
Tired to go through from homepage to checkout manually? Have a script but always having to comment out ''browser.end" is getting very annoying?
Yes. Even for QA. It's hard to debug via SSH as well because of this.  
Lets add a test command that DOESN'T close the browser at the end, even if it fails.
These tests will go from Homepage - Before you Place an Order on checkout.
We also open a new chrome session every-time so that's a plus, we start fresh.
- package.json: add test:e2e-debug which sets a `debug ENV variable`
- Refactored Opening and Closing steps of tests into functions
- Add step numbers to the name of tests and console.log the ENV variable for easier debugging
- npm run test:e2e-debug --tests tests/e2e/workflows/guest-checkout.js
- npm run test:e2e-debug …
=> Add better Debugging for End to End Tests.
