mobify/platform-scaffold

app/components/example/example.jsx, app/containers/app/container.js, app/containers/home/container.js, app/containers/plp/container.js, app/styles/utilities/_flexbox.scss
- Remove unneeded eslint disabler comments
- Remove unnecessary SCSS comment
- Ensure you have the latest version of mobify-code-style in node_modules (you may have to delete it and re `npm install`
- Run `npm run lint`. There should be no errors.
=> Remove comments

package.json, webpack/base.loader.js, webpack/production.js
Add the necessary npm scripts to upload to cloud.
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/83
- Add npm scripts to save API credentials and upload to cloud
- Change output of loader.js to be called adaptive.min.js so that cloud accepts it
- Point the progressive-web-sdk dependency in package.json to the branch in https://github.com/mobify/progressive-web-sdk/pull/83
- `npm install` the progressive-web-sdk
- Get your API key from https://cloud.mobify.com/account/
- Run `npm run save-credentials -- -u youremail@domain.com -k your-api-key`
- Run `npm run push -- -m "upload message"`
- Visit the [progressive web project](https://cloud.mobify.com/projects/progressive-web-scaffold/publishing/production/) in cloud and make sure your bundle is there, and that the preview …
=> Add tasks to upload and save-credentials

circle.yml
- Wait until someone breaks `master` or `develop` and hope that https://circleci.com/docs/configuration/#per-branch-notifications works as expected.
=> Enable CircleCI notifications for develop and master.

package.json
Bump progressive web sdk to 0.0.9
- `npm i`
- Ensure the app still runs fine
- Ensure tests are passing on circleCI
=> Update SDK to v0.0.9

.eslintrc.yml, app/containers/plp/container.js, app/main.jsx
This PR fixes the current failures in develop by ensuring that all files containing JSX import React. 
- Add React imports to PLP and main.jsx 
- Add eslint rule requiring React in scope for JSX code.
- npm run dev
- See that preview works
- npm run lint:js
- See that there are no errors
=> Explicit react everywhere

CHANGELOG.md, package.json
* Base: `master`
* Compare: `release-vX.Y.Z`
Paste the contents of this checklist into this pull request.
* Tag version: `X.Y.Z` @ `master`
* Release title: `X.Y.Z - <release_name>`
* Description: Use highlights from the CHANGELOG.md (only pick out the most significant changes)
=> Release v0.7.1

CHANGELOG.md, package.json
Correct previous 0.7.1 Release
=> Correct previous 0.7.1 Release

package.json
=> Update the progressive-web-sdk dependency to 0.10.3

app/containers/header/container.js, app/containers/header/container.test.js
Tiny PR with some tests.
- Tests for `generateCartCounterBadge`
- Observe they pass
=> Add tests for generateCartCounterBadge

app/containers/cart/actions.js, dev-server/logger.js
Updating Merlin's links to use HTTPS. I didn't change any mocks in tests.
**JIRA** (related): https://mobify.atlassian.net/browse/WEB-991
- Updating Merlin's links to use HTTPS
=> HTTP -> HTTPS

app/styles/_animations.scss, app/styles/_lib.scss, app/styles/animations/_background.scss, app/styles/lib/_background.scss, app/styles/themes/_pw-components.scss, app/styles/themes/pw-components/_skeleton-block.scss, app/styles/themes/pw-components/_skeleton-inline.scss
Add skeleton animations to Merlin's Potions!
- Add background animations for use in the skeletons
- Add theme styles for the SDK skeleton components
- Preview [Merlin's Potions](https://preview.mobify.com/?url=http%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- Confirm that both the block and inline version of the skeletons animate as intended.
=> Skeleton Animations

app/containers/app/container.js, app/containers/header/container.js
`mapDispatchToProps` was not formatted correctly in a recent PR - led to silent feature failure. 
**Linked PRs**: #209 
- Fix `mapDispatchToProps` format for `app` and `header` containers
- Preview
- Make sure you can open the navigation (menu) and mini-cart from the header.
=> Fix header buttons

circle.yml
Apply changes to run on CircleCI 2.0. Please see the linked PR for details.
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/425
The test instructions are the same as in the linked SDK PR.
=> Upgrade to CircleCI 2.0

README.md
Add a few notes to the README
**Linked PRs**: #209 
- Add note about how to create a new component
- Add note about how to trigger a notification
- Read the README 😃
=> Notification and create component notes to README

native/app/app.js, native/app/config/baseConfig.js, native/app/controllers/tabController.js, native/ios/scaffold.xcodeproj/project.pbxproj, native/webpack.app.config.js
Sets up Progressive **App** Scaffold to use Mobify Preview
- (change1)
- (necessary corresponding PRs)
=> Set up Preview for Native Scaffold

app/app-provider.jsx
Route the charms page as a PLP
- Route the charms page as a PLP
- Preview
- Go to charms
- See the skeletons go away
=> Route the charms page as a PLP

native/ios/scaffold.xcodeproj/project.pbxproj
Title says it all
- Update bundle display name
- Install app
- Look at app in home screen
=> Update app name from Scaffold to Merlin's Potions

app/containers/cart/partials/cart-product-list.jsx, tests/system/page-objects/cart.js
Adds a class to the Remove button in the cart for end-to-end testing purposes.
- Adds `qa-cart-remove-item` class to the Remove button in the cart
- Checkout this branch
- `npm install`
- Go to https://www.merlinspotions.com/checkout/cart/ and inspect the 'Remove' button. Verify that it has class `qa-cart-remove-item`
=> Add QA selector to remove item button in cart

web/app/containers/plp/partials/plp-contents.jsx, web/app/containers/plp/partials/product-tile.jsx
This simplifies and clarifies the propType definitions, avoiding some confusion I experienced earlier.
- (change1)
- (necessary corresponding PRs)
=> Pass the product info to the ProductTile as separate props

web/app/containers/checkout-shipping/actions.js, web/app/containers/checkout-shipping/partials/checkout-shipping-form.jsx, web/app/containers/checkout-shipping/partials/shipping-address.jsx, web/app/containers/checkout-shipping/partials/shipping-email.jsx, web/app/containers/checkout-shipping/partials/shipping-method.jsx, web/app/store/checkout/actions.js, web/app/store/checkout/reducer.js, web/app/store/checkout/shipping/selectors.js
This PR addresses some of the design feedback for the checkout shipping page. 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1099
**Linked PRs**: #292 
- Updated email address label text
- Made h4s all caps
- Updated h4 spacing
- Added placeholder text for company and apt fields
- Set first shipping method option to selected by default
- add an item to the cart
- confirm that the items checked off in the JIRA ticket have been fixed correctly
=> WEB-1099: checkout shipping design feedback

web/package.json
Upgrades to the latest SDK before we release the Scaffold.
=> Upgrade to the 0.11.4 SDK version.

web/app/app-provider.jsx, web/app/containers/app/_app.scss, web/app/containers/app/container.js, web/app/containers/checkout-confirmation/_checkout-confirmation.scss, web/app/containers/checkout-confirmation/actions.js, web/app/containers/checkout-confirmation/actions.test.js, web/app/containers/checkout-confirmation/container.js, web/app/containers/checkout-confirmation/partials/checkout-confirmation-details.jsx, web/app/containers/checkout-confirmation/partials/checkout-confirmation-modal.jsx, web/app/containers/checkout-confirmation/partials/checkout-confirmation-questions.jsx, web/app/containers/checkout-confirmation/partials/checkout-confirmation-splash.jsx, web/app/containers/checkout-footer/_checkout-footer.scss, web/app/containers/checkout-footer/container.js, web/app/containers/checkout-header/_checkout-header.scss, web/app/containers/checkout-header/container.js, web/app/styles/utilities/_text.scss
Take Mitch's design feedback and apply it to the Checkout Confirmation page.
**JIRA**: [WEB-1099](https://mobify.atlassian.net/browse/WEB-1099)
- All changes as noted in WEB-1099
- Visit the confirmation page directly (no need to purchase anything) [here](https://www.merlinspotions.com/checkout/confirmation/)
=> Confirmation design feedback

web/app/containers/checkout-shipping/actions.js, web/app/containers/checkout-shipping/partials/shipping-email.jsx, web/app/containers/checkout-shipping/selectors.js
This PR adds some functionality to the email section on the checkout shipping page. Specifically on blur it will check if the email address is known, and show the sign in form if it is. It also adds submission handling for the sign in form.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1111
**Linked PRs**: #292 
- Added onBlur handler to email address field
- Added call to API to check if email address is known
- Added submit handling for the sign in form
- add an item to the cart (as a logged out user)
- enter an email address …
=> Shipping known email

web/app/containers/cart/partials/cart-product-list.jsx
A simple change to make the Sign In button work. For now we're just navigating to the login page.
**JIRA**: https://mobify.atlassian.net/browse/WEB-1110
**Linked PRs**: 
- Add a link to the login page on the Sign In button
- Go to the cart page with something in your cart.
- See that if you click the "Sign In" button in the upper right that you navigate to the login page.
=> Add an href to the `Sign In` button.

web/CHANGELOG.md, web/app/store/cart/actions.js, web/package.json
* Base: `master`
* Compare: `release-vX.Y.Z`
Paste the contents of this checklist into this pull request.
* Tag version: `X.Y.Z` @ `master`
* Release title: `X.Y.Z - <release_name>`
* Description: Use highlights from the CHANGELOG.md (only pick out the most significant changes)
=> Hotfix cart endpoint

web/CHANGELOG.md, web/package.json
Resolving conflicts merging master->develop
=> 0.13.1 changes

native/android/scaffold/src/main/java/com/mobify/astro/merlins/MainActivity.java
Fixes import in Android project 
- Change import in MainActivity from `plugins` to `astro`
=> Move astroworker import to right place

web/app/containers/checkout-shipping/container.jsx
Cart link not working in checkout progress bar
- fix cart link in progress bar
- Proceed to checkout to get to shipping page then click on cart in progress bar
=> fix cart link in checkout progress bar

web/app/styles/themes/pw-components/_field.scss
Radio buttons out of alignment
- align radio button 
- Proceed to checkout and scroll to shipping method
=> fix radio alignment

web/app/containers/cart/partials/cart-product-list.jsx
Cart heading not formatted correctly, see mock
- fix cart heading to match design 
=> fix cart heading to match design

web/app/components/product-item/index.jsx, web/app/containers/cart/partials/cart-product-list.jsx
Product title formatting in cart card is not matching mocks
- fix product title to match mocks
=> Fix cart product title

native/app/config/cartConfig.js, native/app/controllers/cartHeaderController.js
Use the center icon in checkout instead of the header
**JIRA**: https://mobify.atlassian.net/browse/HYB-1024
- Set the center icon of the header bar plugin instead of the center text
=> Use merlins potions logo in header bar

web/README.md
Typo fix.
**JIRA**: none
**Linked PRs**: none
- `deply` --> `deploy`
- N/A
=> fix typo in readme

web/CHANGELOG.md, web/README.md, web/package.json
Update references to this repo in docs within this repo. #meta
- Fixed README.md
=> Fix repo name for this repo

web/app/containers/checkout-header/container.js, web/app/router.jsx
Remove sign in button from payment step
- remove sign in from payment and confirmation steps
- go through the checout
=> fix checkout header for payment and confirmation steps

web/package.json
- Move Web Font Loader to dependencies, since it's required at run time
- ?
=> Move webfontloader to dependencies

web/app/containers/header/_header.scss, web/app/containers/header/partials/stores-action.jsx, web/app/styles/themes/pw-components/_header-bar.scss
Link store locator to https://locations.merlinspotions.com/
**JIRA**: https://mobify.atlassian.net/browse/WEB-1151
- click on stores in header
=> WEB-1151: store locator goes to https://locations.merlinspotions.com/

web/app/template.jsx
"Welcome Back" banner when going through checkout on Merlin's with a previously registered email showing up on every step of checkout
**JIRA**: https://mobify.atlassian.net/browse/WEB-1290
- call removeAllNotifications when route changes
- go to shipping and enter "mobifyqa@gmail.co" for email 
- continue to payment
=> WEB-1290: banner showing on every step of checkout

web/README.md
Fixing docs to point to correct file
=> Fixing README for connectors

web/app/containers/login/partials/common.jsx, web/app/containers/login/partials/register-form.jsx, web/app/containers/login/partials/register-panel.jsx, web/app/containers/login/partials/signin-panel.jsx
Login and register page front end polish
**JIRA**: https://mobify.atlassian.net/browse/WEB-1345
- remove headings
- remove background color
- remove * and required text 
- go to Login/Register
=> WEB-1345: update login and register to match mocks

web/app/containers/product-list/_product-list.scss, web/app/containers/product-list/partials/product-list-contents.jsx, web/app/containers/product-list/selectors.js, web/app/store/categories/actions.js, web/app/store/categories/parsers/product-list.js, web/app/store/categories/parsers/product-list.test.html, web/app/store/categories/parsers/product-list.test.js, web/app/store/categories/reducer.js, web/app/utils/parser-utils.js, web/app/utils/sort-utils.js
sort filter implementation
**JIRA**: https://mobify.atlassian.net/browse/WEB-1337
- Implement sort utils and use it in selectors to sort products 
- have to finalize the UI after filter is added 
- go to PLP and sort
=> Web 1337  sort

web/app/containers/checkout-payment/partials/credit-card-form.jsx
Add placeholder to expiry date 
**JIRA**: N/A
- add 'mm/yy' to expiry date field
- Add an item to cart and continue to payment
=> add placeholder to expiry date

native/package.json
Updates `mobify-progressive-app-sdk` to the release candidate for version 1.0.
- Update package.json
- `git clean -Xfd`
- `cd native && npm run deps`
- Should build fine
=> Update to rc1 of astro

web/app/main.jsx
As it says on the box. 
- (change1)
=> Make Merlins the configured connector

web/CHANGELOG.md, web/RELEASE.md, web/package.json, web/scripts/lighthouse-ci.sh, web/yarn.lock
This hotfix is needed to fix certificate issues with the lighthouse tests!
* Base: `master`
* Compare: `release-vX.Y.Z`
Paste the contents of this checklist into this pull request.
* Tag version: `X.Y.Z` @ `master`
* Release title: `X.Y.Z - <release_name>`
* Description: Use highlights from the CHANGELOG.md (only pick out the most significant changes)
=> Release v0.16.4

web/app/containers/cart/actions.js
error was not showing in promo notifications
- fix notifications for submit and remove promo 
- Apply invalid promo
=> fix promo notifications

amp/app/containers/home/_home.scss, amp/app/containers/home/container.jsx, amp/app/containers/home/home.scss, amp/app/containers/pdp/_pdp.scss, amp/app/containers/pdp/container.jsx, amp/app/containers/pdp/pdp.scss, amp/app/containers/plp/_plp.scss, amp/app/containers/plp/container.jsx, amp/app/containers/plp/plp.scss, amp/app/main.js
**JIRA**: https://mobify.atlassian.net/browse/AMP-53
- Up to developers to ensure that the correct component-styles are included on a page-by-page basis for now.
- Preview http://localhost:3000/ and http://localhost:3000/potions/eye-of-newt.html
- Check make sure have it's own unique styles
=> Build and include different stylesheets for each rendered page.

web/app/containers/header/partials/cart-action.jsx, web/tests/system/page-objects/cart.js
remove hard coded url for removing cart 
**JIRA**: https://mobify.atlassian.net/browse/WEB-1386
- remove URL and navigate to cart using mini cart
- run `npm run test:e2e --tests`
=> remove hard coded url for removing cart

web/app/connector-extension/cart/command-overrides.js, web/app/main.jsx
Overrides the update cart quantity command on Merlin's as an example of command overrides.
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-79
**Linked PRs**: https://github.com/mobify/platform-scaffold/pull/639
- Overrides the update cart quantity command on Merlin's
- Use merlin's connector
- Add an item to your cart
- Ensure updating cart quantity still works!
=> [Integration Manager] - command override example

web/app/utils/analytics/client-analytics.js
Replace example analytic implementation with newer version
- Update example file
1. Run `npm run dev`
2. Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
Expected: Nothing breaks
=> Fix analytics example base

web/app/utils/analytics/client-analytics.js
- Missed some changes
1. Run `npm run dev`
2. Preview [Merlin's Potions](https://preview.mobify.com/?url=https%3A%2F%2Fwww.merlinspotions.com%2F&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
Expected: Nothing breaks
=> miss some fix

web/app/router.jsx
JIRA: WEBDATA-105
How to test: 
Follow bug report in WEBDATA-105
=> Add missing SFCC category routes

web/app/integration-manager/cart/commands.js, web/app/loader.js, web/package.json
This PR bumps the minimum SDK version to 0.15.1 to match the new release (which fixes things).
=> Update the SDK version.

web/app/containers/checkout-payment/actions.js, web/app/containers/checkout-payment/partials/checkout-payment-form.jsx, web/app/containers/checkout-shipping/partials/checkout-shipping-form.jsx, web/app/integration-manager/_merlins-connector/checkout/commands.js, web/app/utils/utils.js
This PR adds an error message when users enter an incomplete full name (ie. first name only). It also adds validation to the billing address form (including the incomplete full name error), and updates how we split full names. 
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-114
- Added full name validation to shipping & billing forms
- Updated split names function to better support double barrelled last names (split Joe De Magio into firstname: Joe lastname: De Magio)
- follow the steps in the ticket (be sure to enter only one name "Mobify" on the shipping form)
=> [WEBDATA-114] Merlins checkout address failure

web/app/containers/cart/container.jsx, web/app/integration-manager/_merlins-connector/cart/cart-contents-parse-cart-expected.json, web/app/integration-manager/_merlins-connector/cart/parser.js
Edit Button and Continue Shopping Unresponsive
**JIRA**: https://mobify.atlassian.net/browse/WEB-1415
- Add configureUrl to items object in parseCart 
- Go to cart and click on edit
=> Web 1415-  Edit Button and Continue Shopping Unresponsive

web/app/containers/checkout-shipping/actions.js
Guest Checkout - Focus, Unfocus Email Form Field shows the password field and a notification
**JIRA**: https://mobify.atlassian.net/browse/WEB-1414
- Add a check for empty username
- Add an item to cart and continue to shipping step
- Check that registered email is only triggers the notification
=> Add a check for empty username

web/app/containers/checkout-confirmation/actions.js, web/app/integration-manager/_merlins-connector/account/commands.js
(brief description / PR title)
**JIRA**: https://mobify.atlassian.net/browse/WEBDATA-120
- Remove the duplicate password test in the checkout confirmation register action (thanks @jnurse)
- Cut down the Magento error with embedded HTML for our purposes.
- Try to register with an email address that already has an account
- See that the error message doesn't contain raw HTML.
=> [WEBDATA-120] Trim magento stuff

web/package.json
=> Bump SDK to version 0.15.2

web/CHANGELOG.md, web/package.json
- Add `messaging:testmessage` command to `web/package.json`
**JIRA**: https://mobify.atlassian.net/browse/MSG-481
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/656
- Add `messaging:testmessage` command to `web/package.json`
- Using the matching SDK PR, verify that the `npm run messaging:testmessage` command works (see the SDK Messaging docs)
=> Add `messaging:testmessage` command

web/DEVELOPING.md, web/app/init-stub-connector.js, web/app/main.jsx
**JIRA**: N/A
- Updates the documentation to reflect the latest connector changes
=> Update DEVELOPING.md & main.jsx with stub connector

amp/app/containers/app/_app.scss, amp/app/containers/app/_base.scss, amp/app/containers/app/container.jsx, amp/app/containers/home/_home.scss, amp/app/containers/home/container.jsx, amp/app/containers/home/container.scss, amp/app/containers/product-list/_product-list.scss, amp/app/containers/product-list/container.jsx, amp/app/containers/product-list/container.scss, amp/app/styles/themes/amp-components/_price.scss, amp/app/styles/themes/amp-components/_product-tile.scss
💇  Stylin' 💅  the PLP List View 😎  💯 
**JIRA**: https://mobify.atlassian.net/browse/AMP-61
- Added `ProductTile` component to `product-list` container
- Cleaned up `product-list` and `home` containers, removed unneeded elements
- Added padding to `app` container so content appears below header
- Visit `localhost:3000` and `localhost:3000/potions.html`
=> AMP-61: PLP List

amp/DEVELOPING.md
DNS setup is going to have to be a manual setup step as far as I can see. No code changes here - just notes in the `DEVELOPING.md` and links to the relevant parts of the AWS documentation.
=> Add notes for DNS/SSL config to DEVELOPING.md

amp/README.md
- Updates to README.md with how to install, and how to test
- Read the readme
=> Simple docs updates for how to set up AMP and run tests

web/tests/system/nightwatch-config.js, web/tests/system/page-objects/push-messaging.js, web/tests/system/workflows/push-subscribe.js
- Add a test script to capture subscribe flow
- Browser config to always accept the browser ask
- Rebuild https://circleci.com/gh/mobify/platform-scaffold/tree/test-push
=> Add e2e test for subscribing to browser notifications

web/package.json
- Update SDK version to 0.15.5
- ~~(if applicable) analytics events instrumented to measure impact of change~~
- Run `npm update progressive-web-sdk`
- **Verify** the app works as expected
=> upgrade sdk version to 0.15.5

web/app/modals/navigation/reducer.js
=> [Hotfix] Ensure "sign in" does not behave as a category

web/scripts/wait-for-dependencies.sh
Lets get those Master tests green!!
*CHANGES:
** Problem is I was failing because the test-server check was in place still even when on Master (production). A test-server does not actually start up when on Production. Trying this now to exit out of the script if the branch is on Master.
=> Master test hotfix

amp/app/containers/product-details/_container.scss, amp/app/containers/product-details/container.jsx, amp/app/containers/product-details/partials/product-details-description.jsx
Added product description
**JIRA**: https://mobify.atlassian.net/browse/AMP-73
- Added product description
- Preview [Merlin's Potions](http://localhost:3000/potions/eye-of-newt.html)
=> AMP-73: product description

amp/app/containers/navigation/container.jsx, amp/app/containers/product-details/container.jsx, amp/app/containers/product-details/partials/product-details-add-to-cart.jsx
Add Select Options and Buy button
**JIRA**: https://mobify.atlassian.net/browse/AMP-72
- Preview [Merlin's Potions](http://localhost:3000/potions/eye-of-newt.html)
=> AMP-72: Select Options and Buy button

amp/app/containers/product-list/partials/product-list-contents.jsx
Make PLP product links work
- PLP product links -> PWA
- Check out http://localhost:3000/potions.html
- Click some products
=> PLP product links -> PWA

web/app/components/notification/test.js, web/package-lock.json, web/package.json, web/tests/system/page-objects/checkout.js, web/tests/system/workflows/registered-checkout.js
As the label says.
- (change1)
=> Upgrade to v0.16.0 of SDK

amp/app/containers/product-details/partials/product-details-carousel.jsx
Right now on https://amp.merlinspotions.com/eye-of-newt.html the left and right arrows don't show up. This PR fixes that.
- Use `staticURL`
- Check out the PDP
=> Fix chevron assets when deployed

web/app/containers/footer/_footer.scss, web/app/containers/footer/partials/newsletter-form.jsx, web/app/containers/header/container.jsx, web/app/loader.js
For the past while, Lighthouse has been reporting a number of accessibility issues, and this PR aims to fix (most of) them!
**Linked PRs**: [progressive-web-sdk#737](https://github.com/mobify/progressive-web-sdk/pull/737)
| Lighthouse Audit |
| --- |
| ![screen shot 2017-07-07 at 10 27 16 am](https://user-images.githubusercontent.com/734535/27969281-1ce7bafa-62ff-11e7-8c7b-5a3729d2a2e5.png) |
- Add accessible text to buttons that were missing text
- Add missing label to newsletter signup form
- Remove inaccessible meta properties
- "Inaccessible meta properties" means removing `user-scalable="no"` from our viewport meta tag, and increasing the `maximum-scale` to `5.0`. A reminder that this is **a Google recommendation!** See their explanation below:
| Google's Accessible Meta Tag Audit | …
=> [Lighthouse Audit] A11y Fixes

web/package.json
update SDK version to 0.17.2
- update SDK version to 0.17.2
=> update SDK version to 0.17.2

web/app/store/index.js
=> update merlin’s ga id

web/package.json
=> Update merlin ga

web/app/containers/product-details/partials/product-details-add-to-cart.jsx, web/app/containers/product-details/partials/product-details-variations.jsx
https://mobify.atlassian.net/browse/WEB-1423
**JIRA**: https://mobify.atlassian.net/browse/WEB-1423
- fix padding on PDP add to cart form
=> fix padding in PDP form

amp/app/containers/product-list/container.jsx, amp/app/containers/product-list/partials/product-list-contents.jsx, amp/app/containers/product-list/partials/product-list-filter-modal.jsx, web/CHANGELOG.md, web/app/connectors/_merlins-connector/app/commands.js, web/app/connectors/_merlins-connector/categories/commands.js, web/app/connectors/_merlins-connector/categories/parser.js, web/app/connectors/_merlins-connector/config.js, web/app/connectors/_sfcc-connector/app/commands.js, web/app/connectors/_sfcc-connector/categories/commands.js, web/app/connectors/_sfcc-connector/config.js, web/app/connectors/_sfcc-connector/parsers.js, web/app/containers/product-list/_product-list.scss, web/app/containers/product-list/constants.js, web/app/containers/product-list/partials/product-list-contents.jsx, web/app/containers/product-list/partials/product-list-header.jsx, web/app/containers/product-list/selectors.js, web/app/init-merlins-connector.js, web/app/modals/product-list-filter/container.jsx, web/app/router.jsx, web/app/store/categories/actions.js, web/app/store/categories/reducer.js, web/app/store/categories/selectors.js, web/app/styles/themes/_pw-components.scss, web/app/styles/themes/pw-components/_pagination.scss, web/app/utils/utils.js, web/package.json, web/tests/performance/lighthouse/check-lighthouse-score.js
Update `amp` with latest from `develop`
- Update with latest changes from `develop`
- Fix a bunch of selectors that got renamed (https://github.com/mobify/platform-scaffold/commit/2e2028ff4b6704fc15839aa9c129dae9bb9e32af)
- Check out http://localhost:3000/potions.html http://localhost:3000/eye-of-newt.html
=> AMP catch up with develop - July 21 2017 edition

web/CHANGELOG.md, web/app/containers/onboarding/_onboarding.scss, web/app/containers/onboarding/container.jsx
(Onboarding styles are hidden/broken)
**JIRA**: https://mobify.atlassian.net/browse/WEB-1479
- (pass active prop to carousel item)
- go to https://localhost:8443/
=> pass active prop to carousel item

web/package.json
=> SDK version bump

web/CHANGELOG.md, web/app/router.jsx
Update to pageview analytics instrumentation
**JIRA**: https://mobify.atlassian.net/browse/MTT-664
**Linked PRs**: https://github.com/mobify/progressive-web-sdk/pull/786
- `npm link progressive-web-sdk` to the analytics-update-lancome branch
- Run `npm run dev:build` in the SDK folder
- Run `npm run dev` in scaffold folder
Make sure pageview events are still working
=> Update where the page view is instrumented

.github/PULL_REQUEST_TEMPLATE.md
- Updates PR template with `npm start` changes)
=> Update PR template with npm start change

amp/DEVELOPING.md
**JIRA**: https://mobify.atlassian.net/browse/AMP-110 
**Linked PR**: https://github.com/mobify/platform-scaffold/pull/918 
**Rreviewers**: @kschmidtdev 
- Adds docs to readme
- Make sure [PR918]( https://github.com/mobify/platform-scaffold/pull/918) works accordingly
- Make sure the docs read right
=> Adds docs for configuring/debugging Mobify/Customer GA.

amp/app/main.js
As fixed and reviewed already on Lancome's build https://github.com/mobify/lancome/pull/240
=> Fix fallthrough in static asset handler

web/app/router.jsx
~**JIRA**: (link to JIRA ticket)~
~**Linked PRs**: (links to corresponding PRs, optional)~
- Added missing SFCC `accountInfo` route
- Use SFCC connector
- Navigate to accountInfo page
=> Added missing SFCC accountInfo route

web/package.json
Reverts mobify/platform-scaffold#964
=> Revert "Point to release-0.20.2 branch of SDK"

web/app/connectors/_sfcc-connector/checkout/utils.js
**JIRA**: https://mobify.atlassian.net/browse/WEB-1514
- Added empty block as first value in countrySelect on SFCC
- use SFCC connector
- Login & navigate to address page
- Add new address
- Fill in everything except Country
- Try to submit
- It should fail
=> Resolved initial values for add-address on SFCC connector

web/app/connectors/_sfcc-connector/parsers.js
SFCC - Missing empty state for My Orders page
**JIRA**: https://mobify.atlassian.net/browse/WEB-1516
- Check for data in parseOrder response
- See ticket for steps
=> WEB-1516- check for data

web/app/connectors/_sfcc-connector/cart/utils.js
Cannot add to cart from Wishlist
**JIRA**: https://mobify.atlassian.net/browse/WEB-1515
- Check for `BasketNotFoundException` when checking for expiredCart
- See ticket for steps
=> Web 1515 add to cart

web/scripts/wait-for-dependencies.sh
(brief description / PR title)
- (change1)
=> Always wait for prod:build and test server to finish

web/CHANGELOG.md, web/app/connectors/_sfcc-connector/config.js, web/app/router.jsx
Logged in state not recognized
**JIRA**: https://mobify.atlassian.net/browse/WEB-1526
- fix dashboard pathname
- login with mobifyqa@gmail.com
- open menu and select my account
=> WEB-1526: fix dashboard pathname
